// ============================================
// TEAM WEEKEND TREKKERS - TRIP DATABASE
// ============================================
// 
// Last updated: 2026-08-10 16:18
// Updated via Trip Manager Mobile App
// ============================================

const tripsData = {
    theyyam: {
        title: "Neelakurinji & Nelji Hills Escape ",
        location: "Madikeri, Karnataka ",
        badge: "Cultural",
        featured: true,
        price: "₹4399",
        image: "images/trips/theyyam_1786994002748.png",
        distance: "300 km from Bangalore",
        elevation: "800-2100",
        difficulty: "Easy",
        bestTime: "Aug - Sept",
        duration: "2D/1N",
        availableDates: ["Aug 7-9, 2026", "Aug 14-16, 2026", "Aug 21-23, 2026", "Aug 28-30, 2026"],
        about: " THE NELJI HILLS EXPERIENCE\n\nExplore one of Coorg's highest peaks on the Nelji Twin Hills Trek, set along the Karnataka–Kerala border. ⛰️\n\nThe 5+5 km trail passes through open grasslands before reaching a summit with sweeping views across the Western Ghats.\n\n\uD83C\uDF38 During the rare Neelakurinji bloom season, the hills take on an unforgettable charm.",
        highlights: ["\uD83C\uDF38 Rare Neelakurinji Blooms — Experience the hills during the special bloom season", "⛰️ Nelji Twin Hills Trek — 5+5 km adventure through scenic grasslands", "\uD83C\uDF04 Karnataka–Kerala Border Views — Panoramic Western Ghats landscapes from the summit", "\uD83C\uDF71 Summit Lunch Experience — Enjoy a packed lunch surrounded by mountains", "\uD83D\uDCA6 Chelavara Waterfalls — Discover a beautiful waterfall tucked away in forest", "\uD83D\uDED5 Igguthappa Temple — Explore one of Coorg’s revered temples", "\uD83C\uDFEF Sri Venugopala Swamy Temple — Historic temple beside the KRS backwaters", "\uD83E\uDEA8 Iconic Stone Chariot — A unique architectural highlight of the temple"],
        itinerary: [
            {day: "\uD83C\uDF19 DAY 0", title: " Friday Night Journey", activities: ["\uD83D\uDE90 Start the overnight journey from Bangalore towards Coorg and Nelji Hills \uD83C\uDF3F", "\uD83D\uDD59 Departure at 10:00 PM", "\uD83C\uDFB6 Settle in, enjoy the road-trip vibes and travel through the night towards the Western Ghats ✨"]},
            {day: "\uD83C\uDF3F DAY 1", title: "Nelji Twin Hills Trek ⛰️", activities: ["☀️ Reach the homestay around 6:00 AM", "\uD83C\uDFE1 Freshen up & enjoy breakfast before heading towards the trek base \uD83C\uDF73", "\uD83E\uDD7E NELJI TWIN HILLS TREK — 5+5 KM", "\uD83C\uDF3F Begin the trek around 9:30 AM through open grasslands along the Karnataka–Kerala border.", "\uD83C\uDF38 During the rare Neelakurinji bloom season, the mountain slopes come alive with beautiful seasonal flowers \uD83D\uDC9C", "⛰️ NELJI HILLS SUMMIT", "Reach the peak around 12:00 PM and take in panoramic views across the Karnataka & Kerala hill ranges ☁️\uD83C\uDF04", "\uD83D\uDCF8 Enjoy the spectacular landscapes and capture some unforgettable summit moments.", "\uD83C\uDF71 Packed Lunch at the Summit", "Enjoy your lunch surrounded by open skies, grasslands and mountain views.", "\uD83E\uDD7E Begin the descent after spending some time at the summit.", "⏰ Trek expected to finish around 4:00 PM", "\uD83C\uDFE1 Return to the homestay, freshen up & relax.", "☕ Enjoy evening tea & snacks.", "\uD83C\uDF7D️ Dinner around 8:30–9:00 PM", "\uD83D\uDD25 Campfire if weather permits.", "\uD83C\uDF19 Rest early and recharge for the next day's exploration."]},
            {day: "\uD83C\uDF04 DAY 2", title: " HIDDEN WATERFALLS, TEMPLES & SCENIC STOPS ✨", activities: ["\uD83C\uDF05 Wake up to a peaceful Coorg morning.", "\uD83C\uDF73 Have breakfast & check out from the homestay.", "\uD83D\uDED5 PAADI SHREE IGGUTHAPPA TEMPLE", "Visit the revered Igguthappa Temple, an important spiritual and cultural landmark of Coorg surrounded by beautiful Western Ghats landscapes \uD83C\uDF3F\uD83D\uDE4F", "\uD83D\uDCA6 CHELAVARA WATERFALLS", "Head towards the spectacular Chelavara Waterfalls, one of Coorg's beautiful hidden gems. \uD83C\uDF27️\uD83D\uDC9A", "Enjoy the refreshing surroundings, spend some time by the falls and capture the beauty of the landscape \uD83D\uDCF8✨", "\uD83C\uDF5B LUNCH BREAK", "Stop for lunch before continuing towards the next destination.", "\uD83C\uDFEF SRI VENUGOPALA SWAMY TEMPLE", "Visit the magnificent Sri Venugopala Swamy Temple near the KRS backwaters.", "✨ Set against the scenic Kaveri River landscape, the temple is known for its beautiful architecture, peaceful surroundings and the iconic stone chariot.", "\uD83C\uDF0A Enjoy the stunning combination of heritage, water and countryside views before beginning the return journey.", "\uD83C\uDF19 RETURN JOURNEY", "Wrap up the weekend and begin the journey back towards Bangalore with muddy shoes, full camera galleries and plenty of memories \uD83D\uDCF8\uD83D\uDC9A", "\uD83C\uDFE1 Reach Bangalore by approximately 10:30 PM"]},
        ],
        includes: ["\uD83D\uDE90 Transportation✔️ Non A/C seater vehicle✔️ Tempo Traveler / Mini Bus / Bus depending on group size", "\uD83C\uDF7D️ Meals✔️ South Indian Vegetarian meals✔️ Day 1 → Breakfast, Packed Lunch, Evening Tea & Snacks & Dinner✔️ Day 2 → Breakfast", "\uD83C\uDFE1 Accommodation✔️ Basic homestay accommodation✔️ Shared rooms / Dormitory", "\uD83E\uDD7E Trek & Other Inclusions✔️ Nelji Hills Forest / Trek Permit✔️ Trek Lead / Trek Support✔️ Packed Lunch for the trek", "✔️ \uD83D\uDDFA️ Local Guide & Outdoor Leader – Knowledgeable experts from TWT to enhance your experience.", "✔️ \uD83C\uDF1F Unforgettable Experiences – Priceless moments, amazing stories, and lifelong memories!"],
        excludes: ["❌ Lunch on Day 2❌ Personal expenses❌ Any meals or beverages not mentioned in inclusions❌ Any additional expenses due to emergencies / natural calamities❌ Travel & Medical Insurance❌ Any additional service, activity or sightseeing"],
        thingsToCarry: ["\uD83C\uDF92 Things to Carry — Nelji Hills Trek \uD83C\uDF3F⛰️\uD83E\uDD7E Trekking Shoes — Good grip is a must, especially during monsoon\uD83C\uDF92 Backpack — Comfortable daypack for the trek\uD83D\uDCA7 Water Bottle — Carry at least 1–2 litres\uD83E\uDDE5 Raincoat / Poncho — Essential for unpredictable Coorg weather\uD83D\uDC55 Extra Clothes — Keep a fresh set after the trek\uD83E\uDDE6 Extra Socks — Carry 2–3 pairs to keep your feet dry\uD83E\uDDE2 Cap / Hat — Useful during sunny stretches\uD83E\uDE74 Slippers / Flip-Flops — For use at the homestay\uD83D\uDD0B Power Bank — Useful during the long journey and trek\uD83D\uDCF1 Phone & Charging Cable — Keep them safely packed\uD83E\uDDF4 Personal Toiletries — Toothbrush, toothpaste, soap, towel, etc.\uD83E\uDE79 Personal Medicines & Basic First Aid — Carry anything you may personally need\uD83D\uDD76️ Sunglasses — Helpful during open grassland sections\uD83E\uDDF4 Sunscreen & Mosquito Repellent — Recommended for outdoor activities\uD83C\uDF6B Energy Snacks — Dry fruits, chocolates, energy bars, etc.\uD83D\uDDD1️ Small Waterproof Bags — For wet clothes, shoes and valuables\uD83D\uDCB5 Extra Cash — For personal expenses and lunch\uD83D\uDCF8 Camera — Optional, but definitely worth carrying for the views! \uD83D\uDC9A⚠️ Trek Essentials❌ Avoid carrying heavy luggage during the trek☔ Keep electronics and valuables inside waterproof covers\uD83E\uDD7E Avoid new shoes — wear comfortable, broken-in trekking shoes\uD83C\uDF27️ Monsoon weather can be unpredictable, so come prepared!"],
        boardingLocations: [
            {name: "1️⃣ Majestic – Shantala Silk & Sarees", landmark: "\uD83D\uDCCD Near Metro Station", time: "10:00 PM", mapLink: "https://maps.app.goo.gl/UtPPeQvWtyVz44GC7"},
            {name: "2️⃣ Old Mysore Road Satellite Bus Stand", landmark: "Adyar Ananda Bhavan ", time: "10:30 PM", mapLink: "https://maps.app.goo.gl/PwvmhPGenVMhGMqh8"},
            {name: "3️⃣ Nayanda Halli", landmark: "Divinity Global Mall", time: "10:50 PM", mapLink: "https://maps.app.goo.gl/tJHuQfjQCc43mM2y8"},
            {name: "4️⃣ Kengeri Metro Station", landmark: "Kengeri Bus Terminal ", time: "11:05 PM", mapLink: "https://maps.app.goo.gl/QmLRb8tPn64LFSu2A"},
        ],
        galleryImages: [],
        groupSize: "12",
        isActive: true,
    },
    wayanad: {
        title: "Offbeat Sakleshpur,Madikeri & Doddhabetta Trek",
        location: "Madikeri, Kerala",
        badge: "Trekking ",
        featured: true,
        price: "₹4,499",
        image: "images/trips/wayanad_1785268798536.png",
        distance: "280 km from Bangalore",
        elevation: "700-2,100 m",
        difficulty: "Easy",
        bestTime: "July - Jan",
        duration: "2D/1N",
        availableDates: ["Aug 7-9, 2026", "Aug 14-16, 2026", "Aug 21-23, 2026", "Aug 28-30, 2026"],
        about: "An offbeat weekend escape through misty mountains, hidden waterfalls, scenic treks, coffee estates, and thrilling jeep rides—all in one unforgettable adventure.",
        highlights: ["Hidden Waterfalls – Take a refreshing dip in pristine waterfalls tucked away in the Western Ghats.", "Doddabetta Trek – Trek through dense forests to a breathtaking summit with panoramic mountain views", "Mallalli Waterfalls – Witness one of Karnataka's most spectacular waterfalls in full flow.", "Coffee Estate Walk – Wander through lush coffee plantations surrounded by mist-covered hills.", "Manjarabad Fort – Explore the historic star-shaped fort overlooking the valleys of Sakleshpur.", "Ancient Shiva Temple – Visit a peaceful temple nestled amidst nature.", "Scenic Western Ghats Drive – Travel through winding roads, misty hills, forests, and coffee plantations."],
        itinerary: [
            {day: "\uD83C\uDF19 DAY 0", title: "Friday Night Departure", activities: ["The adventure begins as we leave Bangalore behind and head toward the misty hills of Coorg. \uD83D\uDE90✨", "Enjoy late-night chai breaks ☕, music \uD83C\uDFB6, fun conversations & road-trip vibes while the city lights slowly make way for the peaceful Western Ghats. \uD83C\uDF3Fey"]},
            {day: "\uD83C\uDF3F DAY 1", title: " Trek, Waterfalls & Campfire", activities: ["Wake up to the fresh mountain air of Coorg. ☀️", "\uD83C\uDFE1 Check into the homestay, freshen up & enjoy a delicious breakfast before starting the day's adventure. \uD83C\uDF73", "\uD83E\uDD7E DODDABETTA TREK", "Walk through dense forests, coffee plantations, rolling hills & scenic mountain trails before reaching breathtaking viewpoints overlooking Coorg. (Approx. 4.5 km each way) \uD83C\uDF3F☁️", "\uD83C\uDF71 Enjoy a packed lunch amidst nature.", "\uD83D\uDED5 Visit the peaceful Shiva Temple and soak in the serene surroundings. \uD83D\uDE4F✨", "\uD83D\uDCA6 HIDDEN WATERFALLS", "Cool off with a refreshing dip in crystal-clear mountain waters surrounded by untouched greenery — one of the most beautiful hidden gems of the trip. \uD83D\uDC9A✨", "\uD83C\uDFE1 Return to the homestay by evening.", "\uD83C\uDF7D️ Relish a delicious dinner before gathering around the campfire for music, games, stories & unforgettable moments beneath the stars. \uD83D\uDD25✨"]},
            {day: "\uD83C\uDF04 DAY 2", title: "Waterfalls, Jeep Ride & Heritage Trail", activities: ["\uD83C\uDF05 Wake up to the refreshing mountain breeze.", "\uD83C\uDF73 Enjoy breakfast and check out.", "\uD83D\uDCA6 Visit Mallalli Waterfalls", "Witness one of Karnataka's most spectacular waterfalls surrounded by lush forests and mist-covered cliffs.", "\uD83D\uDE99 Patla Betta Off-Road Jeep Ride", "Experience an adrenaline-filled jeep ride through rugged mountain trails leading to stunning viewpoints.", "\uD83C\uDF5B Lunch en route (Self-sponsored).", "\uD83C\uDFF0 Visit Manjarabad Fort", "Explore the famous star-shaped fort in Sakleshpur and enjoy panoramic views of the Western Ghats.", "\uD83C\uDFDB️ Visit the magnificent Belur Temple, renowned for its stunning Hoysala architecture.", "OR", "\uD83C\uDF0A Head to Yagachi Adventure Camp for optional water sports and thrilling adventure activities.", "━━━━━━━━━━━━━━━", "\uD83C\uDF19 Return Journey", "Begin the journey back to Bangalore with muddy shoes, beautiful memories, full camera galleries & stories you'll cherish forever. \uD83D\uDC9A✨", "\uD83C\uDFE1 Reach Bangalore by around 10:00 PM"]},
        ],
        includes: ["\uD83D\uDE90 Non-A/C Tempo Traveller / Mini Bus (Based on Group Size)", "\uD83C\uDFE1 Comfortable Cottage Accommodation (Sharing Basis)", "✔️ Day 1 – Breakfast, Packed Lunch & Dinner", "✔️ Day 2 – Breakfast", "\uD83E\uDDED Experienced Local Guide & Trip Leader", "\uD83D\uDC9A An unforgettable  experience!"],
        excludes: ["❌ Lunch on Day 2", "❌ Patla Betta Jeep Ride Charges", "❌ Entry Tickets to Optional Attractions", "❌ Adventure Activities at Yagachi", "❌ Personal Expenses"],
        thingsToCarry: ["\uD83C\uDF27️\uD83C\uDF92  Trip Packing Checklist \uD83C\uDF43Pack smart and stay prepared for a fun, safe, and comfortable adventure! \uD83D\uDC47\uD83C\uDF92 Backpack – Comfortable and easy to carry\uD83D\uDCA7 Water Bottle – Stay hydrated throughout the trek\uD83E\uDDE5 Raincoat / Poncho – A must for monsoon treks (avoid umbrellas while trekking)\uD83D\uDC55 Extra Pair of Clothes – You'll likely get wet\uD83E\uDDE6 Extra Socks – Dry feet = Happy trek\uD83D\uDC5F Good Trekking Shoes – With proper grip for slippery trails\uD83E\uDE74 Flip-flops – For use at the campsite/stay\uD83D\uDCF1 Power Bank – Keep your phone charged\uD83D\uDCF8 Camera (Optional) – Capture the monsoon magic\uD83D\uDCB5 Cash – For personal expenses (network/UPI may not work everywhere)\uD83D\uDC8A Personal Medicines – Along with any essentials you may need\uD83E\uDDF4 Toiletries – Towel, toothbrush, toothpaste, soap/shampoo\uD83D\uDECD️ Plastic Zip-lock Bags – To keep your phone, wallet, and electronics dry✨ Pack light, travel responsibly, and get ready for waterfalls, misty trails, and unforgettable monsoon memories! \uD83C\uDF3F\uD83D\uDC9A"],
        boardingLocations: [
            {name: "Silk Board", landmark: "Metro Station ", time: "10:00 PM", mapLink: " https://maps.app.goo.gl/NMCucfmLann1jp9q7"},
            {name: "Shantala Silk and Sarees", landmark: "Near Majestic Metro Station", time: "11:00 PM", mapLink: "https://maps.app.goo.gl/UtPPeQvWtyVz44GC7"},
            {name: "Rajajinagar", landmark: "Near kapoor cafe", time: "11:40 PM", mapLink: "https://maps.app.goo.gl/dvaMcyfduH2ptLB7A"},
            {name: "Yeshwanthpur", landmark: "Govardhan Theatre", time: "11:45 PM", mapLink: "https://https://maps.app.goo.gl/5PcwLgKHo7jiHTVM8ty+Infosys+Bangalore"},
            {name: "Goraguntepalya", landmark: "Fortis Hospital", time: "11:55 PM", mapLink: "https://maps.app.goo.gl/mvodFMunygmZ2o3k7"},
        ],
        galleryImages: ["images/gallery/wayanad/img_1785268246700.jpg", "images/gallery/wayanad/img_1785268252489.jpg", "images/gallery/wayanad/img_1785268257576.jpg", "images/gallery/wayanad/img_1785268262952.jpg", "images/gallery/wayanad/img_1785268267541.jpg", "images/gallery/wayanad/img_1785268271865.jpg", "images/gallery/wayanad/img_1785268277167.jpg", "images/gallery/wayanad/img_1785268284973.png"],
        groupSize: "12-25",
        isActive: true,
    },
    "rameshwaram-dhanushkodi": {
        title: "Rameshwaram-Dhanushkodi-Thanjavur",
        location: "Tamil Nadu",
        badge: "Heritage",
        featured: true,
        price: "₹5,999",
        image: "images/trips/rameshwaram-dhanushkodi_1771970617638.jpg",
        distance: "550 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "July - Mar",
        duration: "2D/1N",
        availableDates: ["Aug 7-9, 2026", "Aug 14-16, 2026", "Aug 21-23, 2026", "Aug 28-30, 2026"],
        about: "Journey to the sacred island of Rameswaram, where Lord Rama built the legendary bridge to Lanka! Visit the magnificent Ramanathaswamy Temple with its stunning corridor of 1,212 ornate pillars (world's longest!), explore the haunting beauty of Dhanushkodi ghost town, and witness the UNESCO gem Brihadeeswara Temple in Thanjavur.\n\nThis spiritual circuit covers the most sacred sites associated with the Ramayana and the royal Chola heritage.",
        highlights: ["Ramanathaswamy Temple - 12 Jyotirlingas", "Dhanushkodi Ghost Town & Beach", "Pamban Bridge - Iconic sea bridge", "Ram Setu Viewpoint", "Dhanushkodi Lighthouse", "Brihadeeswara Temple (UNESCO)", "Thanjavur Maratha Palace", "Kothanda Ramar Temple"],
        itinerary: [
            {day: "Day 0", title: "Night Departure from Bangalore", activities: ["\uD83D\uDE80 Day 0: Let the Journey Begin!", "\uD83C\uDF19 9:00 PM – Buckle up for an exhilarating overnight road trip from Bangalore \uD83D\uDE90\uD83D\uDCA8", "\uD83D\uDCA4 Cozy up & drift into dreams as tomorrow's adventure calls! ✨\uD83C\uDF0C"]},
            {day: "Day 1", title: "Rameshwaram & Dhanushkodi Coastal Magic", activities: ["\uD83C\uDF1E Day 1: Dive into Rameshwaram’s Coastal Magic", "\uD83C\uDFDD️ Morning vibes – Wake up to salty breezes as we arrive in Rameshwaram \uD83C\uDF0A☀️", "\uD83C\uDFE1 Check-in to a comfy homestay & refresh \uD83D\uDECF️\uD83D\uDEC1", "\uD83C\uDF73 Feast on a delicious Tamil Nadu-style breakfast to kickstart the day \uD83D\uDE0B\uD83C\uDF7D️", "\uD83C\uDF1F Must-Visit Marvels \uD83C\uDF1F", "\uD83C\uDF09 Pamban Bridge – Soak in epic ocean views from this iconic engineering masterpiece \uD83C\uDF0A\uD83D\uDE82", "\uD83D\uDED5 Ramanathaswamy Temple – Step into one of the sacred 12 Jyotirlingas \uD83D\uDE4F", "✨ Wander the world’s longest corridor (1,220 m with 1,212 ornate pillars!) \uD83C\uDFDB️", "\uD83D\uDD49️ Feel the powerful aura where Lord Rama worshipped Lord Shiva post his Lanka victory \uD83D\uDD25\uD83D\uDC51", "\uD83D\uDE98 Dhanushkodi Adventures Await", "\uD83C\uDFDA️ Ghost Town & Beach – Stroll through the mystical ruins of Dhanushkodi \uD83C\uDFD6️\uD83D\uDC7B", "\uD83D\uDE82 Old Railway Station – A hauntingly beautiful glimpse into the past ⏳", "\uD83D\uDD4D Kothanda Ramar Temple – Where Rama crowned Vibhishana as Lanka’s king \uD83D\uDC51\uD83D\uDED5", "\uD83C\uDF09 Ram Setu Viewpoint – Marvel at the legendary floating bridge to Lanka \uD83C\uDFD7️\uD83C\uDF0A", "\uD83C\uDF05 Dhanushkodi Lighthouse – Climb for jaw-dropping panoramic ocean views \uD83D\uDDFA️\uD83D\uDC99", "\uD83C\uDF19 Overnight Stay – Relax, recharge & relive the day’s magic at the hotel \uD83D\uDECF️\uD83C\uDF0C"]},
            {day: "Day 2", title: "Thanjavur Royal Heritage & Return", activities: ["\uD83D\uDD25\uD83D\uDDD3️ Day 2: Spiritual Farewell & Royal Encounters", "\uD83C\uDF05 Rise early & relish a hearty breakfas\uD83C\uDF5B", "\uD83C\uDFE1 Check-out with a heart full of memories \uD83D\uDC99", "\uD83D\uDE97 Off to Thanjavur!", "\uD83C\uDF72 Local Lunch – Indulge in authentic flavors \uD83C\uDF5B", "\uD83C\uDFF0 Thanjavur Maratha Palace – Step into royal grandeur & Maratha history \uD83D\uDC51\uD83C\uDFF0", "\uD83D\uDED5 Brihadeeswara Temple – Behold the splendor of this UNESCO marvel \uD83C\uDF0D✨", "\uD83C\uDF07 Sunset Soak – Witness the majestic temple glow as the sun dips below the horizon \uD83C\uDF1E\uD83C\uDFEF", "\uD83D\uDCDA Saraswathi Mahal Library – Flip through ancient manuscripts in Asia’s oldest library \uD83D\uDCD6", "\uD83C\uDFA8 Thanjavur Art Gallery – Admire Chola bronzes & rich artworks \uD83C\uDFAD\uD83D\uDDBC️", "⛪ Schwartz Church – Visit this historical Maratha-era church ⛪", "\uD83D\uDE90 Return Journey – Embark on an overnight ride back to Bangalore with a heart full of epic stories & memories \uD83C\uDF0C\uD83D\uDC99", "✨ A perfect fusion of spirituality, adventure & heritage – this road trip promises to leave you awe-inspired! \uD83D\uDE80\uD83C\uDF0A\uD83C\uDFF0\uD83D\uDC9B"]},
        ],
        includes: [" \uD83C\uDFE1 Accommodation – Comfortable shared rooms for a cozy stay.", "\uD83C\uDF7D️ 2 Breakfasts – Kickstart your mornings with delicious meals.", " \uD83D\uDE90 Travel in Comfort –  Tempo Traveler / Mini-bus with push-back seats (based on group size) for a hassle-free ride (Bangalore to Bangalore).", "\uD83D\uDE96 Tamil Nadu State Tax – ₹4,000 per Tempo Traveler covered.", "\uD83C\uDF9F️ Entry Charges – All applicable entry fees included.", " \uD83D\uDDFA️ Local Guide & Outdoor Leader – Knowledgeable experts from Team Weekend Trekkers to enhance your experience.", "\uD83C\uDF1F Unforgettable Experiences – Priceless moments, amazing stories, and lifelong memories!"],
        excludes: ["\uD83D\uDEA3‍♂️ Activities – Charges not included.", "\uD83C\uDF7D️ Meals not mentioned – Any additional meals apart from breakfast.", "\uD83D\uDCB8 Personal Expenses – Shopping, tips, and other personal costs.", "\uD83D\uDEE1️ Insurance – No coverage for health, medical, life, or accidental insurance.", "⚠️ Anything not mentioned above – Additional expenses beyond the listed inclusions."],
        thingsToCarry: [],
        boardingLocations: [
            {name: "Majestic", landmark: "Metro Station / Shantala Silks", time: "8:50PM - 8:55 PM", mapLink: "https://maps.google.com/?q=Majestic+Metro+Station+Bangalore"},
            {name: "Koramangala", landmark: "Forum Mall Bus Stop", time: "9:20 PM - 9:30 PM", mapLink: "https://maps.app.goo.gl/gFyRSrbDEwKtDTEm6"},
            {name: "Silk Board", landmark: "Silk Board Junction", time: "9:50 PM - 10:00 PM", mapLink: "https://maps.app.goo.gl/98A2pJN5ojN4MFpn8?g_st=ac"},
            {name: "Electronic City", landmark: "Electronic city Toll gate - Bus Boarding", time: "10:20 PM - 10:35 PM", mapLink: "https://maps.app.goo.gl/kuWaGU5Ag7QCtBLM9"},
        ],
        galleryImages: ["images/gallery/rameshwaram-dhanushkodi/img_1767723242011.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723245384.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723247913.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723252112.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723256822.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723259245.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723262866.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723266548.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723268499.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723271878.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723274641.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723278121.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723280681.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723283648.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723286673.jpg", "images/gallery/rameshwaram-dhanushkodi/img_1767723289999.jpg"],
        groupSize: "12-25 members",
        isActive: true,
    },
    "wayanad-pool-party": {
        title: "Kodachadri & Hidlumane Falls Trek..\uD83E\uDDED",
        location: "Shivmogga, Karnataka ",
        badge: "Trekking ",
        featured: true,
        price: "₹3999",
        image: "images/trips/wayanad-pool-party_1785335515681.png",
        distance: "450 km from Bangalore",
        elevation: "1,200-1,800 m",
        difficulty: "Moderate",
        bestTime: "July - Dec",
        duration: "2D/1N",
        availableDates: ["Aug 7-9, 2026", "Aug 14-16, 2026", "Aug 21-23, 2026", "Aug 28-30, 2026"],
        about: "Escape to the heart of the Western Ghats with a weekend packed with adventure, waterfalls, rainforest trails, scenic viewpoints, an off-road jeep ride, and peaceful Malenadu landscapes. Trek to Kodachadri Peak, unwind at Hidlumane Falls, and return with unforgettable memories.",
        highlights: ["\uD83C\uDF3F Kodachadri Trek – Trek through misty forests to a breathtaking summit.", "\uD83D\uDCA6 Hidlumane Falls – Refresh at a beautiful multi-tiered waterfall.", "\uD83D\uDE99 Jeep Ride (Optional) – Thrilling off-road adventure through forest trails.", "\uD83D\uDCA7 Devagange Ponds – Relax by peaceful natural poo", "\uD83C\uDFEF Nagara Fort – Explore a historic fort with scenic views.", "\uD83C\uDFAC Malgudi Museum (Optional) – Relive the charm of R.K. Narayan's Malgudi.", "\uD83C\uDF3F Rainforest Trails – Walk through lush forests and streams.", "\uD83D\uDCF8 Mountain Views – Capture stunning Western Ghats landscapes.", "\uD83C\uDFE1 Homestay Stay – Enjoy local food and a peaceful stay.", "\uD83D\uDD25 Campfire Night – Good food, music, and great company.", "\uD83D\uDC9A Perfect Weekend – Adventure, nature, and unforgettable memories."],
        itinerary: [
            {day: "\uD83C\uDF19 DAY 0", title: " Friday Night Journey", activities: ["\uD83D\uDE90 Start overnight journey from Bangalore toward the Western Ghats \uD83C\uDF3F", "\uD83C\uDFB6 Highway songs, chai breaks, fun conversations & peaceful road-trip vibes as the city lights slowly disappear and the mountains take over ✨"]},
            {day: "\uD83C\uDF3F DAY 1", title: "Kodachadri Trek & Hidlumane Falls Experience", activities: ["☀️ Reach the homestay early morning", "\uD83C\uDFE1 Freshen up & enjoy breakfast before starting the adventure \uD83C\uDF73✨", "\uD83C\uDF33 Begin the Kodachadri Trek through dense rainforest trails, flowing streams, mist-covered paths & beautiful mountain landscapes ☁️\uD83C\uDF27️", "\uD83D\uDCA6 HIDLUMANE WATERFALLS", "Cold waterfall breeze, fresh mountain water & untouched greenery — one of the most refreshing moments of the trek \uD83D\uDC9A✨", "⛰️ KODACHADRI SUMMIT", "As the climb gets higher, clouds slowly surround the mountains ☁️ Reach the peak and soak in endless Western Ghats views, cool breeze & unforgettable photo moments \uD83D\uDCF8✨", "\uD83D\uDE99 OFF-ROAD JEEP RIDE", "The famous Kodachadri jeep ride is pure fun \uD83D\uDD25 Muddy forest roads, bumpy trails & adventure packed into every turn \uD83C\uDF27️✨", "\uD83C\uDFE1 Return to the homestay by evening", "\uD83C\uDF7D️ Enjoy dinner, relax with the group & spend a peaceful night surrounded by nature \uD83C\uDF3F\uD83D\uDC9A"]},
            {day: "\uD83C\uDF04 DAY 2", title: "Scenic Stops & Return Journey", activities: ["The trek may be over… but the journey isn’t done yet \uD83D\uDC9A", "\uD83C\uDF05 Wake up to a peaceful Malenadu morning", "\uD83C\uDF73 Enjoy breakfast & check out by 8:00 AM", "\uD83D\uDCA7 DEVAGANGE NATURAL PONDS\uD83C\uDF3F", "A hidden natural gem surrounded by greenery \uD83D\uDC9A", "Relax, click photos \uD83D\uDCF8, dip your feet & soak in calm Malenadu vibes away from the crowd ✨", "\uD83C\uDFEF NAGARA FORT (Bidanur Fort)", "Step into history at this majestic 17th-century fort surrounded by greenery & scenic reservoir views \uD83C\uDF27️\uD83D\uDC9A", "Explore ancient ruins, old stone pathways & beautiful viewpoints filled with timeless charm ✨", "\uD83C\uDFAC Optional Stop — Malgudi Museum(time permitting) \uD83D\uDCDA", "A nostalgic little detour into the world of R.K. Narayan’s Malgudi — simple, charming & full of old-school vibes ✨", "\uD83C\uDF5B Stop at Shivamogga for lunch (self-sponsored) before starting the return journey \uD83D\uDE90", "\uD83C\uDF19 Return Journey", "Head back toward Bangalore with muddy shoes, happy hearts, full camera galleries \uD83D\uDCF8 & unforgettable mountain memories \uD83D\uDC9A✨", "\uD83C\uDFE1 Reach Bangalore by around 10:00 PM"]},
        ],
        includes: ["\uD83D\uDE90 Transportation  ✔️ Non A/C seater vehicle  ✔️ Tempo Traveler / Mini Bus / Bus depending on group size ", "\uD83C\uDF7D️Meals  ✔️ South Indian Vegetarian meals  ✔️ Day 1 → Breakfast, Packed Lunch & Dinner  ✔️ Day 2 → Breakfast  ", "\uD83C\uDFE1 Accommodation  ✔️ Basic homestay accommodation  ✔️ Shared rooms / Dormitory / Tents  ", "\uD83D\uDCA6 Falls Entry Fee  ", "\uD83C\uDF9F️ Forest Entry Fee  ", "\uD83E\uDDED Experienced Local Guide & Trip Leader"],
        excludes: ["Any other expenses incurred apart from inclusions  ", "Any meals not mentioned in inclusions  ", "Off road jeep ride", "Any additional expenses due to emergencies / natural calamities  "],
        thingsToCarry: ["\uD83C\uDF27️\uD83C\uDF92 Trip Packing Checklist• \uD83C\uDF92 Backpack• \uD83D\uDCA7 Water Bottle• \uD83E\uDDE5 Raincoat / Poncho• \uD83D\uDC55 Extra Clothes• \uD83E\uDDE6 Extra Socks• \uD83D\uDC5F Trekking Shoes• \uD83E\uDE74 Flip-flops• \uD83D\uDCF1 Power Bank• \uD83D\uDCF8 Camera (Optional)• \uD83D\uDCB5 Cash• \uD83D\uDC8A Personal Medicines• \uD83E\uDDF4 Toiletries• \uD83D\uDECD️ Zip-lock Bags (for electronics)"],
        boardingLocations: [
            {name: "1️⃣  Shantala Silk and Sarees Majestic  ", landmark: "Near Metro Station", time: "9:00 PM - 9:30 PM", mapLink: "https://maps.app.goo.gl/UtPPeQvWtyVz44GC7"},
            {name: "2️⃣ Rajajinagar", landmark: "Near kapoor cafe", time: "10:00 PM", mapLink: "https://maps.app.goo.gl/dvaMcyfduH2ptLB7A"},
            {name: "3️⃣ Yeshwanthpur", landmark: "Govardhan Theatre", time: "10:35 PM", mapLink: "https://maps.app.goo.gl/5PcwLgKHo7jiHTVM8"},
            {name: "4️⃣Goraguntepalya", landmark: "Fortis Hospital", time: "10:50 PM", mapLink: "https://maps.app.goo.gl/mvodFMunygmZ2o3k7"},
        ],
        galleryImages: ["images/gallery/wayanad-pool-party/img_1785359493901.jpg", "images/gallery/wayanad-pool-party/img_1785359498995.png", "images/gallery/wayanad-pool-party/img_1785359512524.jpg", "images/gallery/wayanad-pool-party/img_1785359539753.jpg", "images/gallery/wayanad-pool-party/img_1785359544966.jpg", "images/gallery/wayanad-pool-party/img_1785359558117.jpg", "images/gallery/wayanad-pool-party/img_1785359563207.jpg", "images/gallery/wayanad-pool-party/img_1785359573416.jpg", "images/gallery/wayanad-pool-party/img_1785359599478.jpg", "images/gallery/wayanad-pool-party/img_1785359604621.jpg"],
        groupSize: "12",
        isActive: true,
    },
    "varkala-kochi-christmas": {
        title: "Varkala, Kochi & Alleppey - Long Weekend Special ",
        location: "Kerala",
        badge: "Long Weekend Special ",
        featured: false,
        price: "₹9,999",
        image: "images/trips/varkala-kochi-christmas_1771675162168.png",
        distance: "560 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Dec - June",
        duration: "3D/2N",
        availableDates: ["Sept 11-14, 2026"],
        about: "12 strangers. 1 epic escape. Find freedom on Kerala's coast! From the historic charm of Fort Kochi to the peaceful Alleppey backwaters and boho soul of Varkala, this journey is all about new bonds, coastal chill, and unforgettable memories.\n\nExplore Chinese Fishing Nets, cruise through serene backwaters on a shikara, café-hop on Varkala Cliff, and witness the mighty Jatayu Earth Center - the world's largest bird sculpture!",
        highlights: ["Fort Kochi & Chinese Fishing Nets", "Jew Town & Dutch Palace", "Kashi Art Café", "Alleppey Shikara Boat Ride", "Varkala Cliff & Cafés", "Black Sand Beach sunset", "Kayaking through backwaters", "Jatayu Earth Center"],
        itinerary: [
            {day: "Day 0", title: "Night Groove - Wheels Roll!", activities: ["9:00 PM - Pickup from Majestic Metro Station", "9:40 PM - Koramangala pickup (Kota Kochari)", "10:00 PM - Silk Board pickup", "10:40 PM - Electronic City pickup", "Overnight journey with playlists & bonding"]},
            {day: "Day 1", title: "Kochi Calling - Culture & Coastal Charms", activities: ["Morning - Arrive in Kochi", "Check into cozy homestay & refresh", "Traditional Kerala breakfast - appams & chutneys", "Fort Kochi exploration", "Chinese Fishing Nets photo stop", "St. Francis Church visit", "Jew Town & spice markets", "Dutch Palace murals", "Kashi Art Café - art & coffee", "Lunch at Kochi café", "Sunset at Kochi Beach", "Dinner and overnight stay"]},
            {day: "Day 2", title: "Alleppey Magic & Varkala Vibes", activities: ["Breakfast at homestay", "Drive to Alleppey - Venice of the East", "Shikara boat ride through palm-draped backwaters", "Drive to Varkala", "Lunch with cliff views", "Explore Varkala Cliff - shops & cafés", "Optional: Ayurvedic massage", "Sunset at Black Sand Beach", "Beachside dinner & chill", "Overnight in Varkala"]},
            {day: "Day 3", title: "Jatayu Adventures & Final Feels", activities: ["Sea breeze breakfast", "Beach activities or yoga with a view", "Kayaking through peaceful backwater islands", "Jatayu Earth Center - world", ", ", ", ", ", "]},
        ],
        includes: ["Tempo Traveler/Mini-bus (push-back seats)", "2 Nights accommodation", "3 Breakfasts", "Kerala & TN State Tax", "Toll, parking & entry charges", "Shikara boat ride", "Local guide & outdoor leader", "First aid kit"],
        excludes: ["Water/adventure activities", "Meals other than breakfast", "Personal expenses", "Insurance (medical/accidental/life)", "Anything not mentioned"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: ["images/gallery/varkala-kochi-christmas/img_1771676978497.png", "images/gallery/varkala-kochi-christmas/img_1771676983655.png", "images/gallery/varkala-kochi-christmas/img_1771676987323.png", "images/gallery/varkala-kochi-christmas/img_1771676990840.png", "images/gallery/varkala-kochi-christmas/img_1771676994367.png", "images/gallery/varkala-kochi-christmas/img_1771676997560.png", "images/gallery/varkala-kochi-christmas/img_1771677002985.png", "images/gallery/varkala-kochi-christmas/img_1771677006734.png", "images/gallery/varkala-kochi-christmas/img_1771677010842.png", "images/gallery/varkala-kochi-christmas/img_1771677014893.png", "images/gallery/varkala-kochi-christmas/img_1771677018324.png", "images/gallery/varkala-kochi-christmas/img_1771677021452.png", "images/gallery/varkala-kochi-christmas/img_1771677024669.png"],
        groupSize: "12 members",
        isActive: true,
    },
    "kannur-theyyam": {
        title: "Kannur-Thalassery Theyyam Tour",
        location: "Kannur, Kerala",
        badge: "Cultural",
        featured: false,
        price: "₹5899",
        image: "images/trips/theyyam.jpg",
        distance: "350 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Nov - Apr",
        duration: "2D/1N",
        availableDates: ["Nov 20-22, 2026", "Nov 27-29, 2026", "Dec 4-6, 2026", "Dec 11-13, 2026", "Dec 18-20, 2026", "Dec 25-27, 2026"],
        about: "\uD83C\uDF34 Experience the soul of Kerala on a unique weekend getaway featuring the magical Theyyam ritual, ancient temples, scenic beaches, ferry rides, heritage forts, authentic local cuisine, and unforgettable coastal sunsets.",
        highlights: ["\uD83D\uDD25 Experience the magical Theyyam performance & receive divine blessings", "\uD83D\uDE4F Visit the famous Parassinikadavu Sri Muthappan Temple", "\uD83C\uDF5B Taste the unique Muthappan Temple prasadam & traditional temple lunch", "\uD83C\uDFF0 Explore the historic St. Angelo Fort", "\uD83C\uDF0A Climb the Kannur Lighthouse for stunning Arabian Sea views", "\uD83C\uDFAD Learn the history of Theyyam at the Folk Art Museum", "\uD83C\uDF05 Watch a breathtaking sunset at Payyambalam Beach", "\uD83C\uDFA8 Walk through the colourful Graffiti Street"],
        itinerary: [
            {day: "\uD83C\uDF19 Day 0", title: "Journey Starts", activities: ["\uD83D\uDE90 We’ll leave Bangalore at night in a comfortable vehicle and begin our journey towards Kannur.", "Use this time to relax, enjoy the road trip with the group, and get some sleep — by morning, we’ll be waking up near the beautiful Kerala coast. \uD83D\uDCA4"]},
            {day: "\uD83C\uDF1E Day 1", title: "Exploring Kannur & Theyyam Night", activities: ["\uD83C\uDFD6️ We reach Kannur in the morning, head to our homestay, and freshen up.", "\uD83C\uDF73 After a simple and tasty Kerala breakfast, we start our day slowly and comfortably.", "\uD83D\uDE4F Our first stop is the famous Parassinikadavu Sri Muthappan Temple, known for its peaceful atmosphere and unique traditions.", "\uD83D\uDEA4 We’ll also take a short ferry ride through calm backwaters — a very relaxing experience surrounded by nature.", "\uD83C\uDF5B Here you can taste the temple prasadam — tea, steamed pear, and coconut \uD83E\uDD65", "\uD83C\uDF4C We’ll also experience a traditional temple-style lunch with Kerala rice and banana sambar.", "\uD83C\uDFF0 Later, we visit the historic St. Angelo Fort, followed by Kannur Lighthouse, where you can enjoy beautiful views of the Arabian Sea.", "\uD83C\uDF05 By evening, we unwind at Payyambalam Beach, enjoying the sunset and the relaxed coastal vibe.", "\uD83C\uDF70 We’ll spend some time exploring local cafés and street food spots in Kannur before heading back to the homestay.", "\uD83C\uDFE1 You’ll get time to rest and freshen up before the main highlight of the trip.", "\uD83D\uDD25 Main Highlight — THEYAMM EXPERIENCE", "At night, we visit a local temple where Theyyam is performed.", "You’ll witness powerful rituals, fire performances, traditional music, and the deep spiritual energy of this ancient art form — all from very close.", "This is a full-night cultural experience, something truly rare and unforgettable.", "After the performances, we return to the homestay early morning for some rest."]},
            {day: "\uD83C\uDF04 Day 2", title: " Culture, Beaches & Return", activities: ["\uD83D\uDD25 If you wish, you can watch the early morning Theyyam again before leaving.", "☀️ After breakfast, we check out from the homestay and continue exploring.", "\uD83D\uDCDC We visit the Folk Art Museum, where you’ll learn more about Theyyam and Kerala’s traditional art forms \uD83C\uDFAD", "\uD83C\uDFA8 Then we walk through the colorful Graffiti Street, which is great for photos.", "\uD83C\uDFD6️ Next, we visit Muzhappilangad Drive-in Beach, a unique beach where vehicles can drive along the shoreline.", "\uD83C\uDF74 We’ll stop for authentic Kerala food at a local restaurant.", "\uD83C\uDFEF We also explore the historic Thalassery Fort, spend some relaxed time there, and take photos.", "\uD83C\uDF19 By evening, we begin our journey back to Bangalore — carrying beautiful memories, new friendships, and blessings from the Theyyam experience \uD83D\uDC99"]},
        ],
        includes: ["\uD83C\uDFE8 1 Night Accommodation (Sharing Basis)", "\uD83D\uDE90  Private Vehicle for the Entire Trip", "\uD83C\uDF7D️ 2 Breakfast\uD83C\uDF5B 1 Lunch (Temple Prasadam)", "\uD83E\uDDD1‍\uD83D\uDCBC Experienced Trip Captain", "\uD83D\uDEE3️ Toll, Parking, Driver Allowance & Fuel Charges,Kerala State Tax (₹6000 per tempo traveler)", "\uD83D\uDDFA️ Sightseeing as per the Itinerary", "✔️ A once-in-a-lifetime experience! ✨"],
        excludes: ["Lunch & dinner", "Entry fees", "Personal expenses", "Insurance", "Anything not mentioned"],
        thingsToCarry: [],
        boardingLocations: [
            {name: "Majestic", landmark: "Metro Station / Shantala Silks", time: "8:30 PM - 10:00 PM", mapLink: "https://maps.google.com/?q=Majestic+Metro+Station+Bangalore"},
            {name: "Satelite Bus Stand ", landmark: "Adyar Ananda BhavanOld Mysore Road Satellite Bus Stand.", time: "10:30 PM - 10:40 PM", mapLink: "https://maps.app.goo.gl/PwvmhPGenVMhGMqh8"},
            {name: "Nayandahalli", landmark: "Nayandahalli Mysore Road Metro Station", time: "10:50 PM - 10:55PM", mapLink: "https://maps.app.goo.gl/TZzeaMNCVDyu9wRP7"},
            {name: "Kengeri ", landmark: "Kengeri Bus Terminal Metro Station (11:10)", time: "11:10 PM - 11:15 PM", mapLink: "https://maps.app.goo.gl/QmLRb8tPn64LFSu2A"},
        ],
        galleryImages: ["images/gallery/kannur-theyyam/img_1769058552320.jpg", "images/gallery/kannur-theyyam/img_1769058554371.jpg", "images/gallery/kannur-theyyam/img_1769058558645.jpg", "images/gallery/kannur-theyyam/img_1769058560888.jpg", "images/gallery/kannur-theyyam/img_1769058563106.jpg", "images/gallery/kannur-theyyam/img_1769058564943.jpg", "images/gallery/kannur-theyyam/img_1769058571700.jpg", "images/gallery/kannur-theyyam/img_1769058576005.jpg", "images/gallery/kannur-theyyam/img_1769058579360.jpg", "images/gallery/kannur-theyyam/img_1769058664165.png", "images/gallery/kannur-theyyam/img_1769058667305.jpg", "images/gallery/kannur-theyyam/img_1769058669703.jpg"],
        groupSize: "12-20 members",
        isActive: true,
    },
    dandeli: {
        title: "Dandeli River Adventure",
        location: "Dandeli, Karnataka",
        badge: "Adventure",
        featured: false,
        price: "₹6,997",
        image: "images/trips/dandeli.jpg",
        distance: "480 km from Bangalore",
        elevation: "460 m",
        difficulty: "Moderate",
        bestTime: "Oct - May",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Get your adrenaline pumping at Dandeli - Karnataka's adventure capital! Known for white water rafting on the Kali River, this destination offers a perfect mix of adventure sports and wildlife experiences.\n\nCamp by the river, try rafting through rapids, go kayaking, and spot crocodiles on a coracle ride. Perfect for adventure enthusiasts and nature lovers alike!",
        highlights: ["White water rafting (Grade 2-3)", "Kayaking on Kali River", "Coracle ride", "Jungle safari", "Night camping by river", "Bonfire and BBQ"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Adventure Day", activities: ["6:00 AM - Arrive at Dandeli", "7:00 AM - Check-in, freshen up", "8:00 AM - Breakfast", "9:30 AM - White water rafting (2 hrs)", "12:00 PM - Lunch at camp", "2:00 PM - Kayaking session", "4:00 PM - Coracle ride", "6:00 PM - River jacuzzi", "7:30 PM - Bonfire and BBQ dinner"]},
            {day: "Day 2", title: "Safari & Return", activities: ["6:00 AM - Morning jungle safari", "8:30 AM - Breakfast", "10:00 AM - Syntheri Rocks visit", "12:00 PM - Lunch", "1:00 PM - Departure", "9:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC transportation", "1 Night riverside camp", "All meals", "Rafting, Kayaking, Coracle", "Jungle safari", "Bonfire and BBQ", "All safety equipment"],
        excludes: ["Personal expenses", "Travel insurance", "Additional activities", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: true,
    },
    hampi: {
        title: "Hampi - Anjanadri Hills",
        location: "Hampi, Karnataka",
        badge: "Heritage",
        featured: false,
        price: "₹4,477",
        image: "images/trips/hampi.jpg",
        distance: "350 km from Bangalore",
        elevation: "467 m",
        difficulty: "Easy",
        bestTime: "Oct - Feb",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Step back in time at Hampi, the UNESCO World Heritage Site and capital of the mighty Vijayanagara Empire. This open-air museum features stunning temple architecture, boulder-strewn landscapes, and the sacred Tungabhadra River.\n\nClimb Anjanadri Hill (believed to be Lord Hanuman's birthplace), explore ancient ruins, and witness magical sunsets over the surreal boulder landscape!",
        highlights: ["Anjanadri Hill sunrise trek", "Virupaksha Temple", "Vijaya Vittala Temple & Stone Chariot", "Coracle ride on Tungabhadra", "Hemakuta Hill sunset", "Hippie Island exploration"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Introduction", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Hampi Heritage Walk", activities: ["5:00 AM - Arrive in Hampi", "5:30 AM - Anjanadri Hill sunrise trek", "7:30 AM - Breakfast", "9:00 AM - Virupaksha Temple", "11:00 AM - Vijaya Vittala Temple", "1:00 PM - Lunch", "2:30 PM - Coracle ride", "4:00 PM - Hippie Island exploration", "6:00 PM - Hemakuta Hill sunset", "8:00 PM - Dinner and rest"]},
            {day: "Day 2", title: "More Ruins & Return", activities: ["7:00 AM - Breakfast", "8:30 AM - Queen", ", ", ", ", ", ", ", ", ", "]},
        ],
        includes: ["AC transportation", "1 Night accommodation", "Breakfasts and lunches", "Coracle ride", "Local guide", "All sightseeing"],
        excludes: ["Entry fees to monuments", "Dinner", "Personal expenses", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: true,
    },
    "nandi-hills": {
        title: "Nandi Hills Sunrise",
        location: "Bangalore Rural",
        badge: "Day Trip",
        featured: false,
        price: "₹1,499",
        image: "images/trips/nandi-hills.jpg",
        distance: "60 km from Bangalore",
        elevation: "1,478 m",
        difficulty: "Easy",
        bestTime: "Year round",
        duration: "1 Day",
        availableDates: ["Jan 04, 2026", "Jan 11, 2026", "Jan 18, 2026", "Jan 25, 2026", "Feb 01, 2026", "Feb 08, 2026"],
        about: "Witness the magical sunrise from Nandi Hills, Bangalore's favorite weekend getaway! Just an hour from the city, this ancient hill fortress offers breathtaking views, cool breeze, and a perfect escape from the urban hustle.\n\nCombine it with a visit to Bhoga Nandeeshwara Temple and enjoy cycling or paragliding options. Perfect for early birds and photography enthusiasts!",
        highlights: ["Spectacular sunrise views", "Tipu Sultan", ", ", ", ", ", ", ", "],
        itinerary: [
            {day: "Day 1", title: "Sunrise Trip", activities: ["3:30 AM - Pickup from Bangalore", "4:30 AM - Arrive at Nandi Hills", "5:00 AM - Trek to sunrise point", "5:45 AM - Witness magical sunrise", "7:00 AM - Explore Tipu", ", ", ", ", ", ", ", ", ", ", ", "]},
        ],
        includes: ["AC transportation", "Breakfast", "Entry tickets", "Tour guide"],
        excludes: ["Lunch", "Paragliding/Cycling charges", "Personal expenses", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: true,
    },
    gokarna: {
        title: "Gokarna Beach Trek",
        location: "Gokarna, Karnataka",
        badge: "Beach Trek",
        featured: false,
        price: "₹4,777",
        image: "images/trips/gokarna.jpg",
        distance: "480 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Moderate",
        bestTime: "Oct - Mar",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Experience Gokarna - the quieter, more spiritual cousin of Goa! This temple town offers pristine beaches, beach trekking, and a laid-back vibe perfect for backpackers. Trek between secluded beaches and discover hidden coves.\n\nFrom the sacred Mahabaleshwar Temple to the hippie paradise of Om Beach, experience the best of this coastal gem!",
        highlights: ["Beach trek: Kudle to Paradise", "Om Beach camping", "Mahabaleshwar Temple", "Half Moon Beach", "Paradise Beach", "Sunset at Kudle Beach"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip introduction", "9:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Beach Trek & Exploration", activities: ["6:00 AM - Arrive in Gokarna", "7:00 AM - Freshen up, breakfast", "8:30 AM - Mahabaleshwar Temple", "10:00 AM - Gokarna Beach", "11:00 AM - Beach trek begins", "12:00 PM - Kudle Beach", "1:30 PM - Lunch at beach cafe", "3:00 PM - Continue to Om Beach", "5:00 PM - Half Moon Beach", "6:30 PM - Sunset at Paradise Beach", "8:00 PM - Bonfire dinner at camp"]},
            {day: "Day 2", title: "Morning Beach & Return", activities: ["6:00 AM - Sunrise at beach", "7:30 AM - Swim and relax", "9:00 AM - Breakfast", "10:00 AM - Trek back to Gokarna", "12:00 PM - Lunch", "1:00 PM - Departure", "9:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC Sleeper transport", "1 Night beach camping", "All meals", "Beach trek guide", "Camping gear", "Bonfire"],
        excludes: ["Water sports", "Personal expenses", "Temple donations", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: true,
    },
    pondicherry: {
        title: "Pondicherry Trip",
        location: "Puducherry",
        badge: "Beach/Cultural",
        featured: false,
        price: "₹4,977",
        image: "images/trips/pondicherry.jpg",
        distance: "310 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Oct - Mar",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Experience the French Riviera of the East! Pondicherry charms visitors with its unique blend of French colonial heritage, spiritual centers, pristine beaches, and vibrant cafes. Walk through the yellow-painted French Quarter, feel the peace at Auroville, and enjoy the laid-back beach vibes.\n\nFrom croissants at French bakeries to sunrise at Paradise Beach, Pondicherry offers a perfect blend of culture, spirituality, and relaxation.",
        highlights: ["French Quarter heritage walk", "Auroville Matrimandir visit", "Paradise Beach sunrise", "Promenade Beach evening", "French cafes and cuisine", "Sri Aurobindo Ashram"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Introduction and trip briefing", "10:00 PM - Overnight journey to Pondicherry"]},
            {day: "Day 1", title: "Pondicherry Exploration", activities: ["6:00 AM - Arrive in Pondicherry", "7:00 AM - Paradise Beach sunrise", "8:30 AM - Check-in and breakfast at French cafe", "10:00 AM - Auroville and Matrimandir visit", "1:00 PM - Lunch at Auroville cafe", "3:00 PM - French Quarter heritage walk", "4:30 PM - Sri Aurobindo Ashram", "6:00 PM - Promenade Beach sunset", "7:30 PM - Rock Beach stroll", "8:30 PM - Dinner at French restaurant"]},
            {day: "Day 2", title: "Beach & Return", activities: ["6:00 AM - Optional sunrise at beach", "8:00 AM - Breakfast", "9:30 AM - Serenity Beach visit", "11:00 AM - Shopping at MG Road", "12:30 PM - Lunch", "1:30 PM - Departure for Bangalore", "8:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC transportation", "1 Night hotel stay", "Breakfast", "Paradise Beach boat ride", "Auroville entry", "Local guide"],
        excludes: ["Meals not mentioned", "Shopping", "Personal expenses", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: true,
    },
    "madurai-rameswaram": {
        title: "Madurai-Rameswaram-Thanjavur",
        location: "Tamil Nadu",
        badge: "Heritage",
        featured: false,
        price: "₹8,977",
        image: "images/trips/madurai-rameswaram.jpg",
        distance: "600 km from Bangalore",
        elevation: "Sea level - 100m",
        difficulty: "Easy",
        bestTime: "Oct - Mar",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Embark on a spiritual journey through Tamil Nadu's most magnificent temples! Visit the awe-inspiring Meenakshi Temple in Madurai, take a holy dip at Ramanathaswamy Temple in Rameswaram, and marvel at the architectural wonder of Brihadeeswarar Temple in Thanjavur.\n\nThis heritage trail covers three UNESCO-recognized sites and offers deep insights into Dravidian architecture and South Indian spirituality.",
        highlights: ["Meenakshi Amman Temple", "Ramanathaswamy Temple", "Dhanushkodi ghost town", "Brihadeeswarar Temple (UNESCO)", "Pamban Bridge view", "Traditional Tamil cuisine"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip briefing", "9:00 PM - Overnight journey to Madurai"]},
            {day: "Day 1", title: "Madurai & Rameswaram", activities: ["6:00 AM - Arrive in Madurai", "7:00 AM - Freshen up, breakfast", "8:00 AM - Meenakshi Amman Temple", "11:00 AM - Thirumalai Nayak Palace", "12:30 PM - Lunch", "1:30 PM - Drive to Rameswaram", "4:00 PM - Pamban Bridge photo stop", "5:00 PM - Ramanathaswamy Temple", "7:00 PM - Agni Theertham beach", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 2", title: "Dhanushkodi & Thanjavur", activities: ["5:00 AM - Dhanushkodi sunrise trip", "7:30 AM - Explore ghost town", "9:00 AM - Breakfast", "10:00 AM - Drive to Thanjavur", "2:00 PM - Lunch en route", "4:00 PM - Brihadeeswarar Temple", "6:00 PM - Thanjavur Palace", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 3", title: "Return Journey", activities: ["7:00 AM - Breakfast", "8:00 AM - Saraswathi Mahal Library", "10:00 AM - Departure for Bangalore", "8:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC Sleeper transport", "2 Nights hotel stay", "All meals", "Temple guide", "All sightseeing", "Dhanushkodi jeep"],
        excludes: ["Temple donations", "Special pooja charges", "Personal expenses", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: true,
    },
    ooty: {
        title: "Ooty & Coonoor Trip",
        location: "Nilgiris, Tamil Nadu",
        badge: "Hill Station",
        featured: false,
        price: "₹4,499",
        image: "images/trips/ooty.jpg",
        distance: "280 km from Bangalore",
        elevation: "2,240 m",
        difficulty: "Easy",
        bestTime: "Oct - Jun",
        duration: "2D/1N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 2, 2026", "Feb 7-9, 2026"],
        about: "Escape to the Queen of Hill Stations! Ooty, nestled in the Nilgiri hills, offers colonial charm, toy train rides, tea gardens, and beautiful botanical gardens. Combined with the quieter Coonoor, this trip is perfect for nature lovers.\n\nExperience the famous Nilgiri Mountain Railway, walk through tea estates, and enjoy the pleasant weather year-round!",
        highlights: ["Nilgiri Mountain Railway (Toy Train)", "Ooty Botanical Gardens", "Doddabetta Peak viewpoint", "Tea factory visit", "Ooty Lake boating", "Coonoor Sim", ", ", "s Nose viewpoint", "Lamb"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["10:00 PM - Pickup from Majestic Metro Station", "10:30 PM - Koramangala pickup", "11:00 PM - Silk Board & Electronic City", "Begin journey to Ooty"]},
            {day: "Day 1", title: "Ooty Exploration", activities: ["6:00 AM - Arrive in Ooty", "7:30 AM - Freshen up, breakfast", "9:00 AM - Botanical Gardens", "11:00 AM - Doddabetta Peak", "1:00 PM - Lunch", "2:30 PM - Tea factory visit", "4:00 PM - Toy train to Coonoor", "5:30 PM - Sim", "s Rock", "7:00 PM - Return to Ooty", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 2", title: "Lake, Shopping & Return", activities: ["7:00 AM - Breakfast", "8:30 AM - Ooty Lake boating", "10:00 AM - Rose Garden", "11:30 AM - Local market shopping", "1:00 PM - Lunch and departure", "7:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC transportation", "1 Night hotel stay", "Breakfasts and lunches", "Toy train tickets", "All sightseeing", "Tour guide"],
        excludes: ["Entry fees to gardens", "Boating charges", "Personal expenses", "Dinner"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "12-20 members",
        isActive: false,
    },
    spiti: {
        title: "Spiti Valley Expedition",
        location: "Himachal Pradesh",
        badge: "Expedition",
        featured: false,
        price: "₹18,999",
        image: "images/trips/spiti_1770927697765.jpg",
        distance: "2,100 km from Bangalore",
        elevation: "4,500 m",
        difficulty: "Challenging",
        bestTime: "Jun - Sep",
        duration: "8D/7N",
        availableDates: ["Jun 07-14, 2026", "Jun 21-28, 2026", "Jul 05-12, 2026", "Jul 19-26, 2026", "Aug 02-09, 2026", "Dec 27-29.2026"],
        about: "Embark on a life-changing expedition to Spiti Valley - the Middle Land between Tibet and India. This cold desert mountain valley offers surreal landscapes, ancient monasteries, and some of the most dramatic roads in the world.\n\nCross high-altitude passes, visit 1000-year-old monasteries, and experience the raw beauty of the Trans-Himalayas. This is for true adventurers seeking an off-beat experience!",
        highlights: ["Chandratal Lake camping", "Key Monastery visit", "Kunzum Pass (4,590m)", "World", ", ", ", "],
        itinerary: [
            {day: "Day 1", title: "Bangalore to Delhi", activities: ["Morning flight to Delhi", "Pickup and transfer to hotel", "Evening briefing session", "Overnight in Delhi"]},
            {day: "Day 2", title: "Delhi to Shimla", activities: ["6:00 AM - Depart for Shimla", "3:00 PM - Arrive in Shimla", "Evening - Mall Road walk", "Overnight in Shimla"]},
            {day: "Day 3", title: "Shimla to Nako", activities: ["6:00 AM - Early start", "Cross Kinnaur Valley", "Visit Nako Lake", "Overnight in Nako"]},
            {day: "Day 4-5", title: "Kaza & Monasteries", activities: ["Drive to Kaza via Tabo", "Visit Tabo Monastery", "Explore Key Monastery", "Kibber village excursion", "2 nights in Kaza"]},
            {day: "Day 6", title: "Chandratal Lake", activities: ["Drive to Chandratal", "Cross Kunzum Pass", "Camp by the lake", "Stargazing session"]},
            {day: "Day 7-8", title: "Return Journey", activities: ["Early morning lake visit", "Drive to Manali via Rohtang", "Evening at Mall Road", "Next day flight to Bangalore"]},
        ],
        includes: ["Flights (Bangalore-Delhi-Bangalore)", "All road transportation", "7 Nights accommodation", "All meals during trip", "Camping equipment", "Inner line permits", "Experienced expedition leader"],
        excludes: ["Personal expenses", "Travel insurance (mandatory)", "Tips and gratuities", "Anything not mentioned"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    yercaud: {
        title: "Yercaud Hill Station",
        location: "Salem, Tamil Nadu",
        badge: "Road Trip",
        featured: false,
        price: "₹4,999",
        image: "images/trips/yercaud.jpg",
        distance: "220 km from Bangalore",
        elevation: "1,515 m",
        difficulty: "Easy",
        bestTime: "Year round",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Discover the hidden gem of Tamil Nadu! Yercaud, known as the 'Poor Man's Ooty', offers serene lake views, coffee plantations, and pleasant weather without the crowds. Perfect for a peaceful weekend getaway.\n\nExplore the charming Yercaud Lake, visit ancient temples, and enjoy panoramic views from Lady's Seat. A perfect escape for those seeking tranquility!",
        highlights: ["Yercaud Lake boating", "Pagoda Point views", "Lady", ", ", ", ", ", ", "s Cave exploration"],
        itinerary: [
            {day: "Day 1", title: "Early Morning Departure", activities: ["4:00 AM - Pickup from Bangalore", "8:00 AM - Breakfast en route", "10:00 AM - Arrive in Yercaud", "11:00 AM - Check-in, freshen up", "12:00 PM - Yercaud Lake boating", "1:30 PM - Lunch", "3:00 PM - Pagoda Point & Lady", ", ", ", ", ", "]},
            {day: "Day 2", title: "More Exploration & Return", activities: ["7:00 AM - Breakfast", "8:30 AM - Bear", ", ", ", ", ", ", ", ", ", "]},
        ],
        includes: ["AC transportation", "1 Night hotel stay", "Breakfasts", "Boating tickets", "All sightseeing", "Tour guide"],
        excludes: ["Lunches and dinners", "Entry fees", "Personal expenses", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    munnar: {
        title: "Munnar with Kolukkumalai Sunrise",
        location: "Munnar, Kerala",
        badge: "Hill Station",
        featured: false,
        price: "₹6,277",
        image: "images/trips/munnar.jpg",
        distance: "480 km from Bangalore",
        elevation: "1,600 m",
        difficulty: "Easy",
        bestTime: "Sep - Mar",
        duration: "2D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Experience the tea capital of South India! Munnar's rolling tea gardens, misty mountains, and the world's highest tea plantation at Kolukkumalai make this a must-visit destination. Witness a magical sunrise above the clouds!\n\nThe jeep ride to Kolukkumalai through winding paths is an adventure in itself. Combine with Eravikulam National Park for Nilgiri Tahr sighting!",
        highlights: ["Kolukkumalai sunrise jeep trip", "World", ", ", ", ", ", ", ", "],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Introduction", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Munnar Sightseeing", activities: ["9:00 AM - Arrive in Munnar", "10:00 AM - Check-in, freshen up", "11:00 AM - Eravikulam National Park", "1:30 PM - Kerala lunch", "3:00 PM - Tea Museum", "4:30 PM - Mattupetty Dam", "6:00 PM - Echo Point", "8:00 PM - Dinner and rest"]},
            {day: "Day 2", title: "Kolukkumalai & More", activities: ["3:00 AM - Wake up call", "3:30 AM - Jeep to Kolukkumalai", "5:30 AM - Sunrise above clouds", "7:00 AM - Tea factory tour", "9:00 AM - Return to hotel, breakfast", "11:00 AM - Top Station", "1:00 PM - Lunch", "2:00 PM - Shopping", "3:00 PM - Departure", "11:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC Sleeper transport", "1 Night hotel stay", "All meals", "Kolukkumalai jeep", "All sightseeing", "National park entry"],
        excludes: ["Personal expenses", "Boating charges", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    "gokarna-new-year-party": {
        title: "Gokarna New Year Party",
        location: "Gokarna, Karnataka",
        badge: "New Year Special",
        featured: false,
        price: "₹5,400",
        image: "images/trips/gokarna-new-year-party.jpg",
        distance: "480 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Dec - Jan",
        duration: "3D/2N",
        availableDates: ["Dec 30-Jan 01, 2025-26"],
        about: "Ring in 2026 on a private beach in Gokarna! This exclusive New Year celebration combines pristine beaches, bonfire parties, live DJ, and the magic of counting down to midnight under the stars.\n\nEscape the crowded city celebrations and welcome the new year with sand between your toes, waves crashing nearby, and fellow travelers who share your spirit of adventure!",
        highlights: ["Private beach New Year party", "Bonfire and DJ night", "Midnight countdown on beach", "Beach camping experience", "Multiple beach visits", "Fireworks celebration"],
        itinerary: [
            {day: "Day 0", title: "Night Departure (Dec 30)", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip introduction and New Year excitement", "9:00 PM - Overnight journey to Gokarna"]},
            {day: "Day 1", title: "Beach Exploration (Dec 31)", activities: ["6:00 AM - Arrive in Gokarna", "7:00 AM - Check-in to beach camp, freshen up", "8:00 AM - Breakfast", "10:00 AM - Beach hopping: Kudle, Om Beach", "1:00 PM - Lunch at beach shack", "3:00 PM - Half Moon & Paradise Beach trek", "6:00 PM - Return to camp, freshen up", "8:00 PM - New Year Eve party begins", "9:00 PM - Bonfire, DJ, dance", "11:00 PM - Beach games and countdown prep", "12:00 AM - HAPPY NEW YEAR! Fireworks & celebration"]},
            {day: "Day 2", title: "New Year Day & Return (Jan 1)", activities: ["8:00 AM - Late breakfast (recovery time!)", "10:00 AM - Mahabaleshwar Temple visit", "11:30 AM - Gokarna Beach", "1:00 PM - New Year lunch", "2:00 PM - Departure for Bangalore", "10:00 PM - Arrive in Bangalore with amazing memories"]},
        ],
        includes: ["AC Sleeper transport", "Beach camp accommodation", "All meals", "New Year party with DJ", "Bonfire arrangements", "Beach trek guide"],
        excludes: ["Alcoholic beverages", "Personal expenses", "Water sports", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    "netrani-island-scuba": {
        title: "Netrani Island Scuba Diving",
        location: "Murudeshwar, Karnataka",
        badge: "Adventure",
        featured: false,
        price: "₹7,477",
        image: "images/trips/netrani-island-scuba.jpg",
        distance: "490 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Moderate",
        bestTime: "Oct - May",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Dive into the crystal clear waters of Netrani Island - India's premier scuba diving destination! Also known as Pigeon Island, this heart-shaped island offers visibility up to 30 meters and vibrant marine life including reef sharks, rays, and colorful coral.\n\nNo prior diving experience needed! Our certified PADI instructors will guide you through every step. Also visit the magnificent Murudeshwar Temple with the world's second tallest Shiva statue.",
        highlights: ["Scuba diving at Netrani Island", "30m underwater visibility", "Marine life: sharks, rays, turtles", "Murudeshwar Temple visit", "World", ", "],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing and scuba introduction", "10:00 PM - Overnight journey to Murudeshwar"]},
            {day: "Day 1", title: "Scuba Diving Day", activities: ["6:00 AM - Arrive at Murudeshwar", "7:00 AM - Check-in, freshen up, breakfast", "8:30 AM - Scuba diving briefing and training", "10:00 AM - Boat ride to Netrani Island (1 hour)", "11:30 AM - Scuba diving session (45 mins underwater)", "1:00 PM - Return to shore, lunch", "3:00 PM - Rest and optional snorkeling", "5:00 PM - Murudeshwar Temple visit", "6:30 PM - Sunset at beach", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 2", title: "Temple & Return", activities: ["6:00 AM - Sunrise at Murudeshwar beach", "7:30 AM - Breakfast", "9:00 AM - Explore Murudeshwar Temple complex", "10:30 AM - Shopping for souvenirs", "12:00 PM - Lunch and departure", "8:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC transportation", "1 Night hotel stay", "All meals", "Scuba diving with equipment", "PADI certified instructor", "Boat ride to island", "Temple visit"],
        excludes: ["Underwater photos/videos (₹500 extra)", "Personal expenses", "Travel insurance", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    "alleppey-varkala": {
        title: "Alleppey-Varkala-Athirappilly Falls",
        location: "Kerala",
        badge: "Road Trip",
        featured: false,
        price: "₹9,877",
        image: "images/trips/alleppey-varkala.jpg",
        distance: "560 km from Bangalore",
        elevation: "Sea level - 300m",
        difficulty: "Easy",
        bestTime: "Sep - Mar",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Experience the best of Kerala in one epic road trip! Cruise through the serene Alleppey backwaters on a traditional houseboat, relax at the stunning Varkala cliff beach, and witness the majestic Athirappilly Falls - India's own Niagara.\n\nThis trip combines backwater tranquility, beach vibes, and waterfall adventure for the ultimate Kerala experience.",
        highlights: ["Alleppey houseboat overnight stay", "Varkala cliff beach", "Athirappilly Falls (Bahubali location)", "Kerala backwater cruise", "Traditional Kerala cuisine", "Sunset at Varkala"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip introduction", "9:00 PM - Overnight journey to Alleppey"]},
            {day: "Day 1", title: "Alleppey Houseboat", activities: ["9:00 AM - Arrive in Alleppey", "10:00 AM - Freshen up, breakfast", "12:00 PM - Board traditional houseboat", "12:30 PM - Kerala lunch on houseboat", "1:00 PM - Cruise through backwaters", "4:00 PM - Tea and snacks on deck", "6:00 PM - Sunset on backwaters", "8:00 PM - Dinner on houseboat", "Night - Sleep under stars on deck"]},
            {day: "Day 2", title: "Varkala Beach Day", activities: ["7:00 AM - Wake up to backwater sunrise", "8:00 AM - Breakfast, disembark", "9:00 AM - Drive to Varkala", "12:00 PM - Arrive at Varkala cliff", "1:00 PM - Lunch at cliff cafe", "2:00 PM - Beach time and swimming", "4:00 PM - Cliff walk and cafes", "6:00 PM - Sunset at Varkala cliff", "8:00 PM - Dinner, overnight stay"]},
            {day: "Day 3", title: "Athirappilly Falls & Return", activities: ["6:00 AM - Breakfast", "7:00 AM - Drive to Athirappilly", "11:00 AM - Athirappilly Falls visit", "1:00 PM - Lunch near falls", "2:00 PM - Departure for Bangalore", "10:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC Sleeper transport", "1 Night houseboat (AC)", "1 Night hotel stay", "All meals", "All sightseeing", "Tour guide"],
        excludes: ["Water sports", "Personal expenses", "Entry fees", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    "goa-waterfalls": {
        title: "Goa & Karnataka Waterfalls Trek",
        location: "Goa & Karnataka",
        badge: "Adventure",
        featured: false,
        price: "₹5,477",
        image: "images/trips/goa-waterfalls.jpg",
        distance: "560 km from Bangalore",
        elevation: "Sea level - 600m",
        difficulty: "Moderate",
        bestTime: "Oct - Mar",
        duration: "2D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Combine the best of two worlds - Goa beaches and Karnataka's hidden waterfalls! This unique trip takes you to stunning waterfalls in the Western Ghats and then to the beaches of Goa for the perfect adventure-relaxation combo.\n\nTrek through lush forests to discover cascading waterfalls, take refreshing dips in natural pools, and end your trip with sunset at Goa's beaches.",
        highlights: ["Dudhsagar Falls viewpoint", "Hidden waterfall treks", "Natural pool swimming", "Goa beach exploration", "Western Ghats trekking", "Spice plantation visit"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trek briefing", "9:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Waterfall Treks", activities: ["6:00 AM - Arrive at Karnataka-Goa border", "7:00 AM - Breakfast", "8:00 AM - Trek to hidden waterfalls", "10:00 AM - Swim in natural pools", "12:00 PM - Packed lunch at waterfall", "2:00 PM - Continue to second waterfall", "4:00 PM - Spice plantation visit", "6:00 PM - Drive to Goa", "8:00 PM - Check-in, dinner at beach shack"]},
            {day: "Day 2", title: "Goa Beaches & Return", activities: ["6:00 AM - Sunrise at beach", "8:00 AM - Breakfast", "9:00 AM - Dudhsagar Falls viewpoint", "12:00 PM - Lunch", "1:00 PM - Departure for Bangalore", "10:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC Sleeper transport", "1 Night stay", "All meals", "Trek guide", "Spice plantation entry", "All sightseeing"],
        excludes: ["Water sports", "Personal expenses", "Entry fees", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    "dandeli-netrani-scuba": {
        title: "Dandeli & Netrani Scuba Diving",
        location: "Dandeli & Murudeshwar",
        badge: "Adventure",
        featured: false,
        price: "₹7,497",
        image: "images/trips/dandeli-netrani-scuba.jpg",
        distance: "490 km from Bangalore",
        elevation: "Sea level - 460m",
        difficulty: "Moderate",
        bestTime: "Oct - May",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "The ultimate Karnataka adventure combo! Experience white water rafting on Kali River in Dandeli and then dive into the crystal clear waters of Netrani Island for an unforgettable scuba diving experience.\n\nThis action-packed trip combines river rapids, jungle safari, and underwater exploration - perfect for adrenaline junkies looking for non-stop adventure!",
        highlights: ["White water rafting on Kali River", "Scuba diving at Netrani Island", "Jungle safari in Dandeli", "Murudeshwar Temple visit", "River kayaking", "Marine life exploration"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Adventure briefing", "10:00 PM - Overnight journey to Dandeli"]},
            {day: "Day 1", title: "Dandeli Adventures", activities: ["6:00 AM - Arrive at Dandeli", "7:00 AM - Check-in to riverside camp", "8:00 AM - Breakfast", "9:30 AM - White water rafting (2 hours)", "12:00 PM - Lunch at camp", "2:00 PM - Kayaking session", "4:00 PM - Jungle safari", "6:00 PM - Return to camp", "7:00 PM - Bonfire and BBQ dinner"]},
            {day: "Day 2", title: "Scuba Diving Day", activities: ["5:00 AM - Early departure for Murudeshwar", "8:00 AM - Breakfast en route", "10:00 AM - Scuba diving briefing", "11:00 AM - Boat ride to Netrani Island", "12:00 PM - Scuba diving session", "2:00 PM - Return to shore, lunch", "4:00 PM - Murudeshwar Temple visit", "6:00 PM - Beach sunset", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 3", title: "Return Journey", activities: ["7:00 AM - Breakfast", "8:00 AM - Departure for Bangalore", "6:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC transportation", "2 Nights stay (camp + hotel)", "All meals", "Rafting & Kayaking", "Scuba diving with equipment", "Jungle safari", "All activities"],
        excludes: ["Underwater photos (₹500 extra)", "Personal expenses", "Travel insurance", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    "scuba-day-trip": {
        title: "1 Day Scuba Diving Trip",
        location: "Murudeshwar, Karnataka",
        badge: "Day Trip",
        featured: false,
        price: "₹3,177",
        image: "images/trips/scuba-day-trip.jpg",
        distance: "490 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Moderate",
        bestTime: "Oct - May",
        duration: "1 Day",
        availableDates: ["Jan 11, 2026", "Jan 18, 2026", "Jan 25, 2026", "Feb 01, 2026", "Feb 08, 2026"],
        about: "Experience scuba diving without taking time off! This express trip departs Friday night and gets you diving at Netrani Island by Saturday morning. Perfect for busy professionals who want adventure without sacrificing too many days.\n\nNo experience needed - our PADI certified instructors will have you exploring underwater wonders in no time!",
        highlights: ["Express scuba diving trip", "Netrani Island dive", "PADI certified instructors", "Underwater marine life", "Murudeshwar Temple", "Minimal time commitment"],
        itinerary: [
            {day: "Day 1", title: "Scuba Express", activities: ["12:00 AM - Departure from Bangalore (Friday midnight)", "6:00 AM - Arrive Murudeshwar, freshen up", "7:00 AM - Breakfast", "8:00 AM - Scuba briefing and training", "9:30 AM - Boat to Netrani Island", "10:30 AM - Scuba diving session", "12:30 PM - Return to shore", "1:00 PM - Lunch", "2:30 PM - Murudeshwar Temple visit", "4:00 PM - Departure for Bangalore", "11:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC transportation", "Breakfast and lunch", "Scuba diving with equipment", "PADI instructor", "Boat ride", "Temple visit"],
        excludes: ["Underwater photos/videos", "Personal expenses", "Dinner", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    "wayanad-3-days": {
        title: "Wayanad 3 Days Trip",
        location: "Wayanad, Kerala",
        badge: "Hill Station",
        featured: false,
        price: "₹6,977",
        image: "images/trips/wayanad-3-days.jpg",
        distance: "280 km from Bangalore",
        elevation: "700-2,100 m",
        difficulty: "Easy-Moderate",
        bestTime: "Sep - May",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Explore every corner of Wayanad in this comprehensive 3-day trip! From prehistoric Edakkal Caves to the heart-shaped lake at Chembra Peak, from thundering waterfalls to serene wildlife sanctuaries - this trip covers it all.\n\nWayanad's misty mountains, spice plantations, and diverse wildlife make it one of Kerala's most enchanting destinations. Take your time to soak it all in!",
        highlights: ["Chembra Peak heart-shaped lake", "Edakkal Caves prehistoric art", "Soochipara & Meenmutty Falls", "Wayanad Wildlife Sanctuary", "Banasura Sagar Dam", "Spice & tea plantations"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Caves & Waterfalls", activities: ["5:30 AM - Arrive in Wayanad", "6:30 AM - Check-in, freshen up", "7:30 AM - Breakfast", "9:00 AM - Edakkal Caves trek", "12:00 PM - Lunch", "2:00 PM - Soochipara Waterfalls", "4:30 PM - Meenmutty Falls", "6:30 PM - Return to resort", "8:00 PM - Dinner"]},
            {day: "Day 2", title: "Chembra Peak & Wildlife", activities: ["5:00 AM - Early start for Chembra Peak", "6:00 AM - Trek begins", "9:00 AM - Heart-shaped lake viewpoint", "11:00 AM - Return, late breakfast", "1:00 PM - Lunch", "2:30 PM - Wildlife Safari", "5:00 PM - Banasura Sagar Dam", "6:30 PM - Sunset at dam", "8:00 PM - Bonfire dinner"]},
            {day: "Day 3", title: "Plantations & Return", activities: ["7:00 AM - Breakfast", "8:30 AM - Tea plantation visit", "10:00 AM - Spice garden tour", "11:30 AM - Pookode Lake", "1:00 PM - Lunch and shopping", "2:00 PM - Departure for Bangalore", "9:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC transportation", "2 Nights resort stay", "All meals", "Chembra trek permit", "Wildlife safari", "All sightseeing", "Bonfire"],
        excludes: ["Entry fees", "Boating charges", "Personal expenses", "Tips"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
    kudremukh: {
        title: "Kudremukh Trek",
        location: "Western Ghats, Karnataka",
        badge: "Trek",
        featured: false,
        price: "₹3,990",
        image: "images/trips/kudremukh.jpg",
        distance: "18 km trek",
        elevation: "1,894 m",
        difficulty: "Moderate-Hard",
        bestTime: "Oct - Feb",
        duration: "2D/1N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 2, 2026", "Feb 7-9, 2026"],
        about: "Kudremukh, meaning 'Horse Face' in Kannada, is one of the most beautiful treks in South India. The peak resembles a horse's face when viewed from certain angles. This UNESCO heritage site offers pristine grasslands, shola forests, and stunning views.\n\nTrek through the rolling green hills, cross numerous streams, and camp under the stars in one of the most biodiverse regions of the Western Ghats!",
        highlights: ["UNESCO World Heritage Site", "Rolling grassland meadows", "Unique horse-face peak view", "Night camping experience", "Multiple stream crossings", "Rich biodiversity zone"],
        itinerary: [
            {day: "Day 0", title: "Night Departure from Bangalore", activities: ["10:00 PM - Pickup from Majestic Metro Station", "10:30 PM - Koramangala pickup (Kota Kochari)", "10:50 PM - Silk Board pickup", "11:30 PM - Electronic City pickup", "Trip briefing in vehicle", "Overnight journey to Kudremukh"]},
            {day: "Day 1", title: "Trek Day", activities: ["5:00 AM - Arrive at base, freshen up", "6:00 AM - Breakfast", "7:00 AM - Forest permits and trek start", "10:00 AM - Cross grasslands", "1:00 PM - Lunch break", "3:00 PM - Reach campsite near peak", "5:00 PM - Summit push", "6:30 PM - Sunset from peak", "8:00 PM - Dinner at camp"]},
            {day: "Day 2", title: "Descent & Return", activities: ["5:30 AM - Sunrise at peak", "7:00 AM - Breakfast", "8:00 AM - Begin descent", "12:00 PM - Reach base", "1:00 PM - Lunch", "2:00 PM - Depart for Bangalore", "10:00 PM - Arrive in Bangalore"]},
        ],
        includes: ["AC transportation", "Forest permits", "All meals (2B + 2L + 1D)", "Camping gear", "Trek lead and support", "First aid kit"],
        excludes: ["Personal trekking gear", "Travel insurance", "Personal expenses", "Camera fees"],
        thingsToCarry: [],
        boardingLocations: [
            {name: "Majestic", landmark: "Metro Station / Shantala Silks", time: "8:45 PM - 10:00 PM", mapLink: "https://maps.google.com/?q=Majestic+Metro+Station+Bangalore"},
            {name: "Koramangala", landmark: "Kota Kochari, Opp Forum Mall", time: "9:00 PM - 10:30 PM", mapLink: "https://maps.google.com/?q=Forum+Mall+Koramangala+Bangalore"},
            {name: "Silk Board", landmark: "Silk Board Junction", time: "9:15 PM - 10:45 PM", mapLink: "https://maps.google.com/?q=Silk+Board+Junction+Bangalore"},
            {name: "Electronic City", landmark: "Infosys Gate / Toll Plaza", time: "9:45 PM - 11:15 PM", mapLink: "https://maps.google.com/?q=Electronic+City+Infosys+Bangalore"},
        ],
        galleryImages: [],
        groupSize: "12-20 members",
        isActive: false,
    },
    goa: {
        title: "Goa Beach Backpacking",
        location: "North Goa",
        badge: "Backpacking",
        featured: false,
        price: "₹5,477",
        image: "images/trips/goa.jpg",
        distance: "560 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Oct - Mar",
        duration: "2D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Experience Goa like a true backpacker! This trip covers the best of North Goa - pristine beaches, vibrant nightlife, historic forts, and delicious seafood. Perfect for those looking to explore Goa beyond the usual tourist spots.\n\nFrom the hippie vibes of Anjuna to the Portuguese charm of Old Goa, experience the diverse flavors of India's party capital!",
        highlights: ["Calangute & Baga Beach", "Anjuna Flea Market", "Fort Aguada sunset", "Old Goa churches", "Nightlife experience", "Water sports (optional)"],
        itinerary: [
            {day: "Day 0", title: "Departure from Bangalore", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Introduction", "9:00 PM - Overnight journey to Goa"]},
            {day: "Day 1", title: "North Goa Exploration", activities: ["8:00 AM - Arrive in Goa", "9:00 AM - Check-in, freshen up", "10:30 AM - Calangute Beach", "1:00 PM - Seafood lunch", "3:00 PM - Fort Aguada", "5:00 PM - Candolim Beach", "7:00 PM - Baga Beach sunset", "9:00 PM - Dinner and nightlife"]},
            {day: "Day 2", title: "Old Goa & More Beaches", activities: ["8:00 AM - Breakfast", "9:30 AM - Old Goa churches", "11:00 AM - Anjuna Beach", "1:00 PM - Lunch at beach shack", "3:00 PM - Vagator Beach & Chapora Fort", "6:00 PM - Sunset point", "8:00 PM - Return journey", "6:00 AM - Arrive Bangalore (next day)"]},
        ],
        includes: ["Sleeper bus transport", "1 Night accommodation", "Breakfast", "All sightseeing transport", "Tour coordinator"],
        excludes: ["Meals (except breakfast)", "Water sports", "Entry fees", "Personal expenses", "Nightclub entry"],
        thingsToCarry: [],
        boardingLocations: [
        ],
        galleryImages: [],
        groupSize: "",
        isActive: false,
    },
};

// ============================================
// GET TRIP DATA FUNCTION
// ============================================
// Returns trip data by ID, defaults to first trip if not found
function getTripData(tripId) {
    return tripsData[tripId] || tripsData[Object.keys(tripsData)[0]];
}

// ============================================
// COMMON DATA - PICKUP POINTS
// ============================================
const commonPickupPoints = [
    {
        name: "Majestic",
        landmark: "Metro Station / Shantala Silks",
        time: "8:30 PM - 10:00 PM",
        mapLink: "https://maps.google.com/?q=Majestic+Metro+Station+Bangalore"
    },
    {
        name: "Koramangala",
        landmark: "Kota Kochari, Opp Forum Mall",
        time: "9:00 PM - 10:30 PM",
        mapLink: "https://maps.google.com/?q=Forum+Mall+Koramangala+Bangalore"
    },
    {
        name: "Silk Board",
        landmark: "Silk Board Junction",
        time: "9:15 PM - 10:45 PM",
        mapLink: "https://maps.google.com/?q=Silk+Board+Junction+Bangalore"
    },
    {
        name: "Electronic City",
        landmark: "Infosys Gate / Toll Plaza",
        time: "9:45 PM - 11:15 PM",
        mapLink: "https://maps.google.com/?q=Electronic+City+Infosys+Bangalore"
    }
];

// ============================================
// COMMON DATA - CANCELLATION POLICY (PTU Style - Shows Fee)
// ============================================
const commonCancellationPolicy = [
    {
        days: "7+ days before trip",
        refund: "50%",
        color: "#22c55e"  // Green - least penalty
    },
    {
        days: "3-6 days before trip",
        refund: "70%",
        color: "#f59e0b"  // Orange - medium penalty
    },
    {
        days: "0-2 days before trip",
        refund: "100%",
        color: "#ef4444"  // Red - full penalty (no refund)
    }
];

// ============================================
// COMMON DATA - TRIP GUIDELINES (PTU Style)
// ============================================
const commonGuidelines = [
    {
        icon: "fa-ban",
        title: "No Alcohol or Smoking",
        desc: "Consumption of alcohol and smoking is strictly prohibited during the trip. Violation may result in immediate termination without refund."
    },
    {
        icon: "fa-utensils",
        title: "Dinner Before Boarding",
        desc: "Please have your dinner before boarding the vehicle. We won't stop for dinner breaks during night journeys."
    },
    {
        icon: "fa-bus",
        title: "Travel Arrangements",
        desc: "We use Tempo Travellers or Mini-buses with push-back seats. AC will be on from 7 AM to 7 PM only. Night travel is non-AC."
    },
    {
        icon: "fa-mountain",
        title: "Embrace the Outdoors",
        desc: "This is an adventure trip, not a luxury vacation. Expect basic facilities, unpredictable weather, and some physical activity."
    },
    {
        icon: "fa-seedling",
        title: "Food (Vegetarian/Non-Vegetarian)",
        desc: "All meals provided during the trip are vegetarian/Non-veg based on the situation."
    },
    {
        icon: "fa-leaf",
        title: "Leave No Trace",
        desc: "Respect nature. Don't litter, don't pluck plants, and carry back all your waste. Let's keep our trails clean."
    },
    {
        icon: "fa-suitcase",
        title: "Personal Belongings",
        desc: "Team Weekend Trekkers is not responsible for loss or damage to personal belongings. Keep valuables secure at all times."
    },
    {
        icon: "fa-clock",
        title: "Potential Delays",
        desc: "Travel times are estimates. Traffic, weather, and unforeseen circumstances may cause delays. Please be patient and cooperative."
    }
];

// ============================================
// COMMON DATA - FAQs (PTU Style)
// ============================================
const commonFAQs = [
    {
        q: "How do I book a trip?",
        a: "You can book directly through our website by selecting your preferred date and number of travelers, then completing the payment. Alternatively, you can WhatsApp us at 7019235581 for assistance."
    },
    {
        q: "Is there a WhatsApp group for the trip?",
        a: "Yes! Once your booking is confirmed, you'll be added to a WhatsApp group with fellow travelers and the trip coordinator 2-3 days before the trip."
    },
    {
        q: "Is it safe for solo travelers?",
        a: "Absolutely! Most of our travelers are solo. Our groups are friendly and you'll make great friends. We maintain a balanced male-female ratio on most trips."
    },
    {
        q: "Is it safe for women travelers?",
        a: "Yes, women's safety is our top priority. We have female travelers on almost every trip, and our coordinators ensure a safe and comfortable environment for everyone."
    },
    {
        q: "Are there any discounts available?",
        a: "We offer group discounts for 4+ people booking together. Students and repeat travelers may also get special offers. Contact us on WhatsApp for current deals."
    },
    {
        q: "What should I pack for the trip?",
        a: "Pack light! Essentials include: comfortable clothes, good walking shoes, rain jacket/poncho, water bottle, power bank, personal medicines, toiletries, and a small backpack."
    },
    {
        q: "What is the luggage limit?",
        a: "One backpack (40-50L) per person. Avoid large suitcases as they're difficult to carry on treks and take up space in the vehicle."
    },
    {
        q: "Do I need to be super fit for treks?",
        a: "Basic fitness is required. If you can walk 5-10 km and climb stairs without getting exhausted, you're good! Check the difficulty level on each trip page."
    },
    {
        q: "What if I need to cancel my booking?",
        a: "You can cancel through WhatsApp. Cancellation fees apply: 50% fee (7+ days before), 70% fee (3-6 days before), 100% fee (0-2 days before). Refunds are processed within 5-7 business days."
    },
    {
        q: "What if the trip gets cancelled due to weather?",
        a: "If we cancel due to bad weather or unforeseen circumstances, you'll get a full refund or option to reschedule to another date. Your safety comes first!"
    }
];
