// ============================================
// TEAM WEEKEND TREKKERS - TRIP DATABASE
// ============================================
// 
// Last updated: 2025-12-25 18:03
// 
// 📸 PHOTOS: Put images in images/trips/tripid.jpg
// 💰 PRICES: Change the 'price' field
// 📅 DATES: Update 'availableDates' array
// ➕ NEW TRIP: Copy any trip block, change all fields
// ============================================

const tripsData = {
    netravati: {
        title: "Netravati Peak Trek",
        location: "Western Ghats, Karnataka",
        badge: "Weekend Trek",
        price: "₹4000",
        image: "images/trips/netravati.jpg",
        distance: "15-20 km",
        elevation: "1,420 m",
        difficulty: "Moderate",
        bestTime: "Oct - Feb",
        duration: "2D/1N",
        availableDates: ["Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 08-09, 2026", "Jan 20-22, 2026"],
        about: "Netravati Peak, nestled in the Western Ghats of Karnataka, offers one of the most rewarding weekend treks from Bangalore. This hidden gem takes you through lush forests, pristine streams, and breathtaking viewpoints that remain untouched by mass tourism.\n\nThe trek is perfect for adventure seekers looking to escape the city and immerse themselves in nature. With camping under starlit skies and waking up to misty mountain views, this is an experience you'll cherish forever.",
        highlights: ["Hidden waterfalls along the trail", "Night camping under stars", "Rare bird and wildlife spotting", "Pristine streams for refreshing dips", "360° panoramic views from the peak", "Away from tourist crowds"],
        itinerary: [
            {day: "Day 0", title: "Night Departure from Bangalore.", activities: ["10:00 PM - Pickup from designated Bangalore pickup points", "10:30 PM - Introduction and trip briefing in the vehicle", "11:00 PM - Begin overnight journey to base camp", "Music, bonfire vibes, and getting to know fellow trekkers"]},
            {day: "Day 1", title: "Trek to Summit & Camping", activities: ["5:00 AM - Arrive at base village, freshen up", "6:00 AM - Light breakfast and trek briefing", "7:00 AM - Begin trek through forest trail", "10:00 AM - Cross streams and waterfalls", "1:00 PM - Reach campsite, packed lunch", "3:00 PM - Explore nearby viewpoints", "6:00 PM - Sunset views from the peak", "8:00 PM - Bonfire, dinner, stargazing"]},
            {day: "Day 2", title: "Sunrise, Descent & Return", activities: ["5:30 AM - Wake up for sunrise", "6:00 AM - Witness breathtaking sunrise over clouds", "7:30 AM - Breakfast at campsite", "8:30 AM - Begin descent", "12:00 PM - Reach base, freshen up", "1:00 PM - Lunch and departure", "7:00 PM - Arrive back in Bangalore"]}
        ],
        includes: ["Bangalore to Bangalore transportation (AC vehicle)", "1 Breakfast + 1 Lunch + 1 Dinner", "Camping equipment (tents, sleeping bags)", "Experienced trek lead and support staff", "Forest entry permits", "First aid kit", "Bonfire arrangements"],
        excludes: ["Personal expenses", "Travel insurance", "Any meals not mentioned", "Tips and gratuities", "Anything not mentioned in inclusions"],
        groupSize: "",
    },
    coorg: {
        title: "Coorg with Mandalpatti Peak",
        location: "Kodagu, Karnataka",
        badge: "Road Trip",
        price: "₹4,444",
        image: "images/trips/coorg.jpg",
        distance: "280 km from Bangalore",
        elevation: "1,450 m",
        difficulty: "Easy",
        bestTime: "Sep - Mar",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Experience the Scotland of India! Coorg is a picturesque hill station known for its coffee plantations, misty hills, and rich Kodava culture. The highlight is Mandalpatti Peak offering stunning views of the Western Ghats.\n\nJourney through winding roads surrounded by coffee estates, visit ancient temples, and enjoy local Kodava cuisine. The Jeep ride to Mandalpatti through off-road trails is an adventure in itself!",
        highlights: ["Jeep ride to Mandalpatti Peak", "Coffee plantation walk & tasting", "Abbey Falls visit", "Raja's Seat sunset point", "Authentic Kodava cuisine", "Misty mountain views"],
        itinerary: [
            {day: "Day 0", title: "Night Departure from Bangalore", activities: ["10:00 PM - Pickup from Bangalore", "10:30 PM - Introduction and trip briefing", "11:00 PM - Begin overnight journey to Coorg", "Enjoy music and get to know fellow travelers"]},
            {day: "Day 1", title: "Explore Coorg", activities: ["6:00 AM - Arrive in Coorg, freshen up", "7:30 AM - Breakfast at local restaurant", "9:00 AM - Jeep ride to Mandalpatti Peak", "11:00 AM - Enjoy panoramic views at the peak", "1:00 PM - Lunch with local Kodava cuisine", "3:00 PM - Visit Abbey Falls", "5:00 PM - Coffee plantation walk", "6:30 PM - Sunset at Raja's Seat", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 2", title: "Temple Visit & Return", activities: ["7:00 AM - Breakfast at homestay", "8:30 AM - Visit Talakaveri & Bhagamandala Temple", "11:00 AM - Shopping for coffee and spices", "12:30 PM - Lunch and departure", "7:00 PM - Arrive back in Bangalore"]}
        ],
        includes: ["AC transportation from Bangalore", "1 Night accommodation (Hotel/Homestay)", "2 Breakfasts + 2 Lunches + 1 Dinner", "Jeep ride to Mandalpatti", "All sightseeing as per itinerary", "Experienced tour lead"],
        excludes: ["Personal expenses", "Entry fees to monuments", "Travel insurance", "Tips and gratuities"],
        groupSize: "",
    },
    chikmagalur: {
        title: "Chikmagalur 2 Days Trip",
        location: "Chikmagalur, Karnataka",
        badge: "Hill Station",
        price: "₹4,177",
        image: "images/trips/chikmagalur.jpg",
        distance: "250 km from Bangalore",
        elevation: "1,090 m",
        difficulty: "Easy",
        bestTime: "Sep - Feb",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026", "Dec 27-28"],
        about: "Chikmagalur, the land of coffee, offers a perfect weekend escape with its rolling hills, coffee plantations, and serene waterfalls. Home to the highest peak in Karnataka - Mullayanagiri - this destination combines adventure with relaxation.\n\nExperience the aroma of fresh coffee, trek through misty trails, and witness stunning sunsets over the Western Ghats. A perfect blend of nature, adventure, and tranquility!",
        highlights: ["Mullayanagiri Peak - Highest in Karnataka", "Baba Budangiri Hills", "Coffee estate stay experience", "Hebbe Falls trek", "Z-Point sunset views", "Fresh coffee tasting"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["10:00 PM - Pickup from Bangalore (cool)", "10:30 PM - Trip briefing and introductions", "11:00 PM - Overnight journey begins"]},
            {day: "Day 1", title: "Chikmagalur Exploration", activities: ["5:30 AM - Arrive at Chikmagalur", "6:30 AM - Freshen up and breakfast", "8:00 AM - Drive to Mullayanagiri Peak", "10:00 AM - Trek to the summit", "12:00 PM - Visit Baba Budangiri", "2:00 PM - Lunch at local restaurant", "4:00 PM - Hebbe Falls visit", "6:00 PM - Sunset at Z-Point", "8:00 PM - Dinner and bonfire"]},
            {day: "Day 2", title: "Coffee Trail & Return", activities: ["7:00 AM - Sunrise and breakfast", "9:00 AM - Coffee plantation tour", "11:00 AM - Visit Ayyanakere Lake", "1:00 PM - Lunch and shopping", "2:00 PM - Departure for Bangalore", "8:00 PM - Arrive back in Bangalore"]}
        ],
        includes: ["AC transportation roundtrip", "1 Night stay (Homestay/Resort)", "All meals as mentioned", "Sightseeing as per itinerary", "Trek lead and guide", "Bonfire (weather permitting)"],
        excludes: ["Entry fees", "Personal expenses", "Travel insurance", "Anything not mentioned"],
        groupSize: "",
    },
    kerala: {
        title: "Kerala Backwaters Trip",
        location: "Alleppey, Kerala",
        badge: "Backwaters",
        price: "₹9,877",
        image: "images/trips/kerala.jpg",
        distance: "560 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Sep - Mar",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Experience God's Own Country with this immersive Kerala trip covering Alleppey backwaters, Varkala beach, and the majestic Athirappilly Falls. Cruise through serene backwaters on a traditional houseboat and witness Kerala's natural beauty.\n\nFrom the pristine beaches of Varkala to the thundering Athirappilly waterfalls (India's Niagara), this trip offers the perfect blend of relaxation and adventure!",
        highlights: ["Alleppey houseboat cruise", "Varkala cliff beach", "Athirappilly Falls - Bahubali shooting location", "Traditional Kerala cuisine", "Sunset at Varkala beach", "Backwater village experience"],
        itinerary: [
            {day: "Day 0", title: "Departure from Bangalore", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip introduction", "9:00 PM - Overnight journey to Alleppey"]},
            {day: "Day 1", title: "Alleppey Houseboat Experience", activities: ["9:00 AM - Arrive in Alleppey", "10:00 AM - Freshen up, breakfast", "12:00 PM - Board houseboat", "1:00 PM - Kerala lunch on houseboat", "2:00 PM - Cruise through backwaters", "5:00 PM - Evening tea and snacks", "7:00 PM - Sunset on backwaters", "8:00 PM - Dinner and overnight on houseboat"]},
            {day: "Day 2", title: "Varkala Beach Day", activities: ["7:00 AM - Wake up to backwater views", "8:00 AM - Breakfast and disembark", "10:00 AM - Drive to Varkala", "12:00 PM - Arrive at Varkala cliff", "1:00 PM - Lunch at beach shack", "3:00 PM - Beach time and swimming", "6:00 PM - Sunset at Varkala cliff", "8:00 PM - Dinner, overnight stay"]},
            {day: "Day 3", title: "Athirappilly Falls & Return", activities: ["6:00 AM - Early breakfast", "7:00 AM - Depart for Athirappilly", "11:00 AM - Arrive at Athirappilly Falls", "1:00 PM - Lunch near falls", "2:00 PM - Depart for Bangalore", "10:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC Sleeper transportation", "1 Night houseboat stay (AC)", "1 Night hotel/resort stay", "All meals during trip", "All sightseeing", "Tour lead"],
        excludes: ["Water sports (optional)", "Personal expenses", "Entry fees", "Travel insurance"],
    },
    ooty: {
        title: "Ooty & Coonoor Trip",
        location: "Nilgiris, Tamil Nadu",
        badge: "Hill Station",
        price: "₹4,499",
        image: "images/trips/ooty.jpg",
        distance: "280 km from Bangalore",
        elevation: "2,240 m",
        difficulty: "Easy",
        bestTime: "Oct - Jun",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Escape to the Queen of Hill Stations! Ooty, nestled in the Nilgiri hills, offers colonial charm, toy train rides, tea gardens, and beautiful botanical gardens. Combined with the quieter Coonoor, this trip is perfect for nature lovers.\n\nExperience the famous Nilgiri Mountain Railway, walk through tea estates, and enjoy the pleasant weather year-round!",
        highlights: ["Nilgiri Mountain Railway (Toy Train)", "Ooty Botanical Gardens", "Doddabetta Peak viewpoint", "Tea factory visit", "Ooty Lake boating", "Coonoor Sim's Park"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["10:00 PM - Pickup from Bangalore", "10:30 PM - Introductions", "11:00 PM - Begin journey to Ooty"]},
            {day: "Day 1", title: "Ooty Exploration", activities: ["6:00 AM - Arrive in Ooty", "7:30 AM - Freshen up, breakfast", "9:00 AM - Botanical Gardens", "11:00 AM - Doddabetta Peak", "1:00 PM - Lunch", "2:30 PM - Tea factory visit", "4:00 PM - Toy train to Coonoor", "5:30 PM - Sim's Park, Coonoor", "7:00 PM - Return to Ooty", "8:00 PM - Dinner, overnight stay"]},
            {day: "Day 2", title: "Lake, Shopping & Return", activities: ["7:00 AM - Breakfast", "8:30 AM - Ooty Lake boating", "10:00 AM - Rose Garden", "11:30 AM - Local market shopping", "1:00 PM - Lunch and departure", "7:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "1 Night hotel stay", "Breakfasts and lunches", "Toy train tickets", "All sightseeing", "Tour guide"],
        excludes: ["Entry fees to gardens", "Boating charges", "Personal expenses", "Dinner"],
    },
    spiti: {
        title: "Spiti Valley Expedition",
        location: "Himachal Pradesh",
        badge: "Expedition",
        price: "₹18,999",
        image: "images/trips/spiti.jpg",
        distance: "2,100 km from Bangalore",
        elevation: "4,500 m",
        difficulty: "Challenging",
        bestTime: "Jun - Sep",
        duration: "8D/7N",
        availableDates: ["Jun 07-14, 2026", "Jun 21-28, 2026", "Jul 05-12, 2026", "Jul 19-26, 2026", "Aug 02-09, 2026", "Dec 27-29.2026"],
        about: "Embark on a life-changing expedition to Spiti Valley - the Middle Land between Tibet and India. This cold desert mountain valley offers surreal landscapes, ancient monasteries, and some of the most dramatic roads in the world.\n\nCross high-altitude passes, visit 1000-year-old monasteries, and experience the raw beauty of the Trans-Himalayas. This is for true adventurers seeking an off-beat experience!",
        highlights: ["Chandratal Lake camping", "Key Monastery visit", "Kunzum Pass (4,590m)", "World's highest post office - Hikkim", "Langza fossil village", "Kaza local market exploration"],
        itinerary: [
            {day: "Day 1", title: "Bangalore to Delhi", activities: ["Morning flight to Delhi", "Pickup and transfer to hotel", "Evening briefing session", "Overnight in Delhi"]},
            {day: "Day 2", title: "Delhi to Shimla", activities: ["6:00 AM - Depart for Shimla", "3:00 PM - Arrive in Shimla", "Evening - Mall Road walk", "Overnight in Shimla"]},
            {day: "Day 3", title: "Shimla to Nako", activities: ["6:00 AM - Early start", "Cross Kinnaur Valley", "Visit Nako Lake", "Overnight in Nako"]},
            {day: "Day 4-5", title: "Kaza & Monasteries", activities: ["Drive to Kaza via Tabo", "Visit Tabo Monastery", "Explore Key Monastery", "Kibber village excursion", "2 nights in Kaza"]},
            {day: "Day 6", title: "Chandratal Lake", activities: ["Drive to Chandratal", "Cross Kunzum Pass", "Camp by the lake", "Stargazing session"]},
            {day: "Day 7-8", title: "Return Journey", activities: ["Early morning lake visit", "Drive to Manali via Rohtang", "Evening at Mall Road", "Next day flight to Bangalore"]}
        ],
        includes: ["Flights (Bangalore-Delhi-Bangalore)", "All road transportation", "7 Nights accommodation", "All meals during trip", "Camping equipment", "Inner line permits", "Experienced expedition leader"],
        excludes: ["Personal expenses", "Travel insurance (mandatory)", "Tips and gratuities", "Anything not mentioned"],
        groupSize: "",
    },
    kudremukh: {
        title: "Kudremukh Trek",
        location: "Western Ghats, Karnataka",
        badge: "Trek",
        price: "₹3,999",
        image: "images/trips/kudremukh.jpg",
        distance: "18 km trek",
        elevation: "1,894 m",
        difficulty: "Moderate-Hard",
        bestTime: "Oct - Feb",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Kudremukh, meaning 'Horse Face' in Kannada, is one of the most beautiful treks in South India. The peak resembles a horse's face when viewed from certain angles. This UNESCO heritage site offers pristine grasslands, shola forests, and stunning views.\n\nTrek through the rolling green hills, cross numerous streams, and camp under the stars in one of the most biodiverse regions of the Western Ghats!",
        highlights: ["UNESCO World Heritage Site", "Rolling grassland meadows", "Unique horse-face peak view", "Night camping experience", "Multiple stream crossings", "Rich biodiversity zone"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:30 PM - Pickup from Bangalore", "10:00 PM - Trip briefing", "10:30 PM - Overnight journey to Kudremukh"]},
            {day: "Day 1", title: "Trek Day", activities: ["5:00 AM - Arrive at base, freshen up", "6:00 AM - Breakfast", "7:00 AM - Forest permits and trek start", "10:00 AM - Cross grasslands", "1:00 PM - Lunch break", "3:00 PM - Reach campsite near peak", "5:00 PM - Summit push", "6:30 PM - Sunset from peak", "8:00 PM - Dinner at camp"]},
            {day: "Day 2", title: "Descent & Return", activities: ["5:30 AM - Sunrise at peak", "7:00 AM - Breakfast", "8:00 AM - Begin descent", "12:00 PM - Reach base", "1:00 PM - Lunch", "2:00 PM - Depart for Bangalore", "9:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "Forest permits", "All meals (2B + 2L + 1D)", "Camping gear", "Trek lead and support", "First aid"],
        excludes: ["Personal trekking gear", "Travel insurance", "Personal expenses", "Camera fees"],
    },
    goa: {
        title: "Goa Beach Backpacking",
        location: "North Goa",
        badge: "Backpacking",
        price: "₹5,477",
        image: "images/trips/goa.jpg",
        distance: "560 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Oct - Mar",
        duration: "2D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Experience Goa like a true backpacker! This trip covers the best of North Goa - pristine beaches, vibrant nightlife, historic forts, and delicious seafood. Perfect for those looking to explore Goa beyond the usual tourist spots.\n\nFrom the hippie vibes of Anjuna to the Portuguese charm of Old Goa, experience the diverse flavors of India's party capital!",
        highlights: ["Calangute & Baga Beach", "Anjuna Flea Market", "Fort Aguada sunset", "Old Goa churches", "Nightlife experience", "Water sports (optional)"],
        itinerary: [
            {day: "Day 0", title: "Departure from Bangalore", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Introduction", "9:00 PM - Overnight journey to Goa"]},
            {day: "Day 1", title: "North Goa Exploration", activities: ["8:00 AM - Arrive in Goa", "9:00 AM - Check-in, freshen up", "10:30 AM - Calangute Beach", "1:00 PM - Seafood lunch", "3:00 PM - Fort Aguada", "5:00 PM - Candolim Beach", "7:00 PM - Baga Beach sunset", "9:00 PM - Dinner and nightlife"]},
            {day: "Day 2", title: "Old Goa & More Beaches", activities: ["8:00 AM - Breakfast", "9:30 AM - Old Goa churches", "11:00 AM - Anjuna Beach", "1:00 PM - Lunch at beach shack", "3:00 PM - Vagator Beach & Chapora Fort", "6:00 PM - Sunset point", "8:00 PM - Return journey", "6:00 AM - Arrive Bangalore (next day)"]}
        ],
        includes: ["Sleeper bus transport", "1 Night accommodation", "Breakfast", "All sightseeing transport", "Tour coordinator"],
        excludes: ["Meals (except breakfast)", "Water sports", "Entry fees", "Personal expenses", "Nightclub entry"],
    },
    dandeli: {
        title: "Dandeli River Adventure",
        location: "Dandeli, Karnataka",
        badge: "Adventure",
        price: "₹6,997",
        image: "images/trips/dandeli.jpg",
        distance: "480 km from Bangalore",
        elevation: "460 m",
        difficulty: "Moderate",
        bestTime: "Oct - May",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Get your adrenaline pumping at Dandeli - Karnataka's adventure capital! Known for white water rafting on the Kali River, this destination offers a perfect mix of adventure sports and wildlife experiences.\n\nCamp by the river, try rafting through rapids, go kayaking, and spot crocodiles on a coracle ride. Perfect for adventure enthusiasts and nature lovers alike!",
        highlights: ["White water rafting (Grade 2-3)", "Kayaking on Kali River", "Coracle ride", "Jungle safari", "Night camping by river", "Bonfire and BBQ"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Adventure Day", activities: ["6:00 AM - Arrive at Dandeli", "7:00 AM - Check-in, freshen up", "8:00 AM - Breakfast", "9:30 AM - White water rafting (2 hrs)", "12:00 PM - Lunch at camp", "2:00 PM - Kayaking session", "4:00 PM - Coracle ride", "6:00 PM - River jacuzzi", "7:30 PM - Bonfire and BBQ dinner"]},
            {day: "Day 2", title: "Safari & Return", activities: ["6:00 AM - Morning jungle safari", "8:30 AM - Breakfast", "10:00 AM - Syntheri Rocks visit", "12:00 PM - Lunch", "1:00 PM - Departure", "9:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "1 Night riverside camp", "All meals", "Rafting, Kayaking, Coracle", "Jungle safari", "Bonfire and BBQ", "All safety equipment"],
        excludes: ["Personal expenses", "Travel insurance", "Additional activities", "Tips"],
    },
    hampi: {
        title: "Hampi - Anjanadri Hills",
        location: "Hampi, Karnataka",
        badge: "Heritage",
        price: "₹4,477",
        image: "images/trips/hampi.jpg",
        distance: "350 km from Bangalore",
        elevation: "467 m",
        difficulty: "Easy",
        bestTime: "Oct - Feb",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Step back in time at Hampi, the UNESCO World Heritage Site and capital of the mighty Vijayanagara Empire. This open-air museum features stunning temple architecture, boulder-strewn landscapes, and the sacred Tungabhadra River.\n\nClimb Anjanadri Hill (believed to be Lord Hanuman's birthplace), explore ancient ruins, and witness magical sunsets over the surreal boulder landscape!",
        highlights: ["Anjanadri Hill sunrise trek", "Virupaksha Temple", "Vijaya Vittala Temple & Stone Chariot", "Coracle ride on Tungabhadra", "Hemakuta Hill sunset", "Hippie Island exploration"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Introduction", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Hampi Heritage Walk", activities: ["5:00 AM - Arrive in Hampi", "5:30 AM - Anjanadri Hill sunrise trek", "7:30 AM - Breakfast", "9:00 AM - Virupaksha Temple", "11:00 AM - Vijaya Vittala Temple", "1:00 PM - Lunch", "2:30 PM - Coracle ride", "4:00 PM - Hippie Island exploration", "6:00 PM - Hemakuta Hill sunset", "8:00 PM - Dinner and rest"]},
            {day: "Day 2", title: "More Ruins & Return", activities: ["7:00 AM - Breakfast", "8:30 AM - Queen's Bath", "9:30 AM - Elephant Stables", "10:30 AM - Underground Shiva Temple", "12:00 PM - Lunch", "1:00 PM - Departure", "8:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "1 Night accommodation", "Breakfasts and lunches", "Coracle ride", "Local guide", "All sightseeing"],
        excludes: ["Entry fees to monuments", "Dinner", "Personal expenses", "Tips"],
    },
    yercaud: {
        title: "Yercaud Hill Station",
        location: "Salem, Tamil Nadu",
        badge: "Road Trip",
        price: "₹4,999",
        image: "images/trips/yercaud.jpg",
        distance: "220 km from Bangalore",
        elevation: "1,515 m",
        difficulty: "Easy",
        bestTime: "Year round",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Discover the hidden gem of Tamil Nadu! Yercaud, known as the 'Poor Man's Ooty', offers serene lake views, coffee plantations, and pleasant weather without the crowds. Perfect for a peaceful weekend getaway.\n\nExplore the charming Yercaud Lake, visit ancient temples, and enjoy panoramic views from Lady's Seat. A perfect escape for those seeking tranquility!",
        highlights: ["Yercaud Lake boating", "Pagoda Point views", "Lady's Seat viewpoint", "Shevaroy Temple", "Coffee and spice gardens", "Bear's Cave exploration"],
        itinerary: [
            {day: "Day 1", title: "Early Morning Departure", activities: ["4:00 AM - Pickup from Bangalore", "8:00 AM - Breakfast en route", "10:00 AM - Arrive in Yercaud", "11:00 AM - Check-in, freshen up", "12:00 PM - Yercaud Lake boating", "1:30 PM - Lunch", "3:00 PM - Pagoda Point & Lady's Seat", "5:00 PM - Shevaroy Temple", "6:30 PM - Sunset point", "8:00 PM - Dinner and rest"]},
            {day: "Day 2", title: "More Exploration & Return", activities: ["7:00 AM - Breakfast", "8:30 AM - Bear's Cave", "10:00 AM - Coffee plantation visit", "11:30 AM - Local market shopping", "1:00 PM - Lunch", "2:00 PM - Departure", "7:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "1 Night hotel stay", "Breakfasts", "Boating tickets", "All sightseeing", "Tour guide"],
        excludes: ["Lunches and dinners", "Entry fees", "Personal expenses", "Tips"],
    },
    "nandi-hills": {
        title: "Nandi Hills Sunrise",
        location: "Bangalore Rural",
        badge: "Day Trip",
        price: "₹1,499",
        image: "images/trips/nandi-hills.jpg",
        distance: "60 km from Bangalore",
        elevation: "1,478 m",
        difficulty: "Easy",
        bestTime: "Year round",
        duration: "1 Day",
        availableDates: ["Jan 04, 2026", "Jan 11, 2026", "Jan 18, 2026", "Jan 25, 2026", "Feb 01, 2026", "Feb 08, 2026"],
        about: "Witness the magical sunrise from Nandi Hills, Bangalore's favorite weekend getaway! Just an hour from the city, this ancient hill fortress offers breathtaking views, cool breeze, and a perfect escape from the urban hustle.\n\nCombine it with a visit to Bhoga Nandeeshwara Temple and enjoy cycling or paragliding options. Perfect for early birds and photography enthusiasts!",
        highlights: ["Spectacular sunrise views", "Tipu Sultan's Summer Palace", "Bhoga Nandeeshwara Temple", "Cycling trails", "Paragliding (optional)", "Photography paradise"],
        itinerary: [
            {day: "Day 1", title: "Sunrise Trip", activities: ["3:30 AM - Pickup from Bangalore", "4:30 AM - Arrive at Nandi Hills", "5:00 AM - Trek to sunrise point", "5:45 AM - Witness magical sunrise", "7:00 AM - Explore Tipu's Drop", "8:00 AM - Breakfast at hilltop", "9:30 AM - Bhoga Nandeeshwara Temple", "11:00 AM - Optional: Cycling/Paragliding", "1:00 PM - Lunch", "2:30 PM - Departure", "4:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "Breakfast", "Entry tickets", "Tour guide"],
        excludes: ["Lunch", "Paragliding/Cycling charges", "Personal expenses", "Tips"],
    },
    gokarna: {
        title: "Gokarna Beach Trek",
        location: "Gokarna, Karnataka",
        badge: "Beach Trek",
        price: "₹4,777",
        image: "images/trips/gokarna.jpg",
        distance: "480 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Moderate",
        bestTime: "Oct - Mar",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Experience Gokarna - the quieter, more spiritual cousin of Goa! This temple town offers pristine beaches, beach trekking, and a laid-back vibe perfect for backpackers. Trek between secluded beaches and discover hidden coves.\n\nFrom the sacred Mahabaleshwar Temple to the hippie paradise of Om Beach, experience the best of this coastal gem!",
        highlights: ["Beach trek: Kudle to Paradise", "Om Beach camping", "Mahabaleshwar Temple", "Half Moon Beach", "Paradise Beach", "Sunset at Kudle Beach"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip introduction", "9:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Beach Trek & Exploration", activities: ["6:00 AM - Arrive in Gokarna", "7:00 AM - Freshen up, breakfast", "8:30 AM - Mahabaleshwar Temple", "10:00 AM - Gokarna Beach", "11:00 AM - Beach trek begins", "12:00 PM - Kudle Beach", "1:30 PM - Lunch at beach cafe", "3:00 PM - Continue to Om Beach", "5:00 PM - Half Moon Beach", "6:30 PM - Sunset at Paradise Beach", "8:00 PM - Bonfire dinner at camp"]},
            {day: "Day 2", title: "Morning Beach & Return", activities: ["6:00 AM - Sunrise at beach", "7:30 AM - Swim and relax", "9:00 AM - Breakfast", "10:00 AM - Trek back to Gokarna", "12:00 PM - Lunch", "1:00 PM - Departure", "9:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC Sleeper transport", "1 Night beach camping", "All meals", "Beach trek guide", "Camping gear", "Bonfire"],
        excludes: ["Water sports", "Personal expenses", "Temple donations", "Tips"],
    },
    wayanad: {
        title: "Wayanad 2 Days Trip",
        location: "Wayanad, Kerala",
        badge: "Hill Station",
        price: "₹4,877",
        image: "images/trips/wayanad.jpg",
        distance: "280 km from Bangalore",
        elevation: "700-2,100 m",
        difficulty: "Easy",
        bestTime: "Oct - May",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Jan 30-31,2026"],
        about: "Explore the green paradise of Wayanad in Kerala! This hill district offers ancient caves, stunning waterfalls, wildlife sanctuaries, and spice plantations. Perfect for nature lovers and adventure seekers alike.\n\nFrom the historic Edakkal Caves to the misty Chembra Peak, Wayanad offers diverse experiences in a compact destination!",
        highlights: ["Edakkal Caves prehistoric art", "Soochipara Waterfalls", "Wayanad Wildlife Sanctuary", "Banasura Sagar Dam", "Spice plantation visit", "Chembra Peak heart-shaped lake"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Wayanad Exploration", activities: ["5:30 AM - Arrive in Wayanad", "6:30 AM - Freshen up, breakfast", "8:00 AM - Edakkal Caves trek", "11:00 AM - Soochipara Waterfalls", "1:00 PM - Kerala lunch", "2:30 PM - Banasura Sagar Dam", "4:30 PM - Spice plantation tour", "6:00 PM - Check-in to resort", "8:00 PM - Dinner"]},
            {day: "Day 2", title: "Safari & Return", activities: ["6:00 AM - Wildlife safari", "8:30 AM - Breakfast", "10:00 AM - Pookode Lake", "11:30 AM - Shopping", "1:00 PM - Lunch and departure", "8:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "1 Night resort stay", "All meals", "Wildlife safari", "All sightseeing", "Tour guide"],
        excludes: ["Entry fees", "Boating charges", "Personal expenses", "Tips"],
        groupSize: "",
    },
    munnar: {
        title: "Munnar with Kolukkumalai Sunrise",
        location: "Munnar, Kerala",
        badge: "Hill Station",
        price: "₹6,277",
        image: "images/trips/munnar.jpg",
        distance: "480 km from Bangalore",
        elevation: "1,600 m",
        difficulty: "Easy",
        bestTime: "Sep - Mar",
        duration: "2D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Experience the tea capital of South India! Munnar's rolling tea gardens, misty mountains, and the world's highest tea plantation at Kolukkumalai make this a must-visit destination. Witness a magical sunrise above the clouds!\n\nThe jeep ride to Kolukkumalai through winding paths is an adventure in itself. Combine with Eravikulam National Park for Nilgiri Tahr sighting!",
        highlights: ["Kolukkumalai sunrise jeep trip", "World's highest tea plantation", "Eravikulam National Park", "Tea Museum visit", "Mattupetty Dam", "Top Station viewpoint"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Introduction", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Munnar Sightseeing", activities: ["9:00 AM - Arrive in Munnar", "10:00 AM - Check-in, freshen up", "11:00 AM - Eravikulam National Park", "1:30 PM - Kerala lunch", "3:00 PM - Tea Museum", "4:30 PM - Mattupetty Dam", "6:00 PM - Echo Point", "8:00 PM - Dinner and rest"]},
            {day: "Day 2", title: "Kolukkumalai & More", activities: ["3:00 AM - Wake up call", "3:30 AM - Jeep to Kolukkumalai", "5:30 AM - Sunrise above clouds", "7:00 AM - Tea factory tour", "9:00 AM - Return to hotel, breakfast", "11:00 AM - Top Station", "1:00 PM - Lunch", "2:00 PM - Shopping", "3:00 PM - Departure", "11:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC Sleeper transport", "1 Night hotel stay", "All meals", "Kolukkumalai jeep", "All sightseeing", "National park entry"],
        excludes: ["Personal expenses", "Boating charges", "Tips"],
    },
    theyyam: {
        title: "Kannur Theyyam Tour",
        location: "Kannur, Kerala",
        badge: "Cultural",
        price: "₹5,977",
        image: "images/trips/theyyam.jpg",
        distance: "340 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Oct - May",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Witness the spectacular Theyyam ritual - a 800-year-old living tradition of North Kerala! This divine art form combines dance, music, and spiritual possession in colorful costumes. A truly unique cultural experience!\n\nExplore the beautiful Kannur coastline, visit ancient temples, and experience authentic Kerala cuisine. The Theyyam performance will leave you spellbound!",
        highlights: ["Live Theyyam performance", "Kannur Fort (St. Angelo)", "Payyambalam Beach", "Muzhappilangad Drive-in Beach", "Traditional Kerala meals", "Folklore museum"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Kannur & Theyyam", activities: ["6:00 AM - Arrive in Kannur", "7:00 AM - Freshen up, breakfast", "9:00 AM - Kannur Fort", "11:00 AM - Payyambalam Beach", "1:00 PM - Traditional Kerala lunch", "3:00 PM - Muzhappilangad Beach", "5:00 PM - Folklore museum", "7:00 PM - Theyyam temple visit", "8:00 PM - Witness Theyyam ritual", "10:00 PM - Dinner and rest"]},
            {day: "Day 2", title: "More Theyyam & Return", activities: ["5:00 AM - Early morning Theyyam", "8:00 AM - Breakfast", "9:30 AM - Temple visits", "11:00 AM - Local market", "12:30 PM - Lunch", "1:30 PM - Departure", "9:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC Sleeper transport", "1 Night stay", "All meals", "Theyyam temple visits", "All sightseeing", "Local guide"],
        excludes: ["Temple donations", "Personal expenses", "Tips"],
    },
    "gokarna-new-year-party": {
        title: "Gokarna New Year Party",
        location: "Gokarna, Karnataka",
        badge: "New Year Special",
        price: "₹5,400",
        image: "images/trips/gokarna-new-year-party.jpg",
        distance: "480 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Dec - Jan",
        duration: "3D/2N",
        availableDates: ["Dec 30-Jan 01, 2025-26"],
        about: "Ring in 2026 on a private beach in Gokarna! This exclusive New Year celebration combines pristine beaches, bonfire parties, live DJ, and the magic of counting down to midnight under the stars.\n\nEscape the crowded city celebrations and welcome the new year with sand between your toes, waves crashing nearby, and fellow travelers who share your spirit of adventure!",
        highlights: ["Private beach New Year party", "Bonfire and DJ night", "Midnight countdown on beach", "Beach camping experience", "Multiple beach visits", "Fireworks celebration"],
        itinerary: [
            {day: "Day 0", title: "Night Departure (Dec 30)", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip introduction and New Year excitement", "9:00 PM - Overnight journey to Gokarna"]},
            {day: "Day 1", title: "Beach Exploration (Dec 31)", activities: ["6:00 AM - Arrive in Gokarna", "7:00 AM - Check-in to beach camp, freshen up", "8:00 AM - Breakfast", "10:00 AM - Beach hopping: Kudle, Om Beach", "1:00 PM - Lunch at beach shack", "3:00 PM - Half Moon & Paradise Beach trek", "6:00 PM - Return to camp, freshen up", "8:00 PM - New Year Eve party begins", "9:00 PM - Bonfire, DJ, dance", "11:00 PM - Beach games and countdown prep", "12:00 AM - HAPPY NEW YEAR! Fireworks & celebration"]},
            {day: "Day 2", title: "New Year Day & Return (Jan 1)", activities: ["8:00 AM - Late breakfast (recovery time!)", "10:00 AM - Mahabaleshwar Temple visit", "11:30 AM - Gokarna Beach", "1:00 PM - New Year lunch", "2:00 PM - Departure for Bangalore", "10:00 PM - Arrive in Bangalore with amazing memories"]}
        ],
        includes: ["AC Sleeper transport", "Beach camp accommodation", "All meals", "New Year party with DJ", "Bonfire arrangements", "Beach trek guide"],
        excludes: ["Alcoholic beverages", "Personal expenses", "Water sports", "Tips"],
        groupSize: "",
    },
    "netrani-island-scuba": {
        title: "Netrani Island Scuba Diving",
        location: "Murudeshwar, Karnataka",
        badge: "Adventure",
        price: "₹7,477",
        image: "images/trips/netrani-island-scuba.jpg",
        distance: "490 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Moderate",
        bestTime: "Oct - May",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Dive into the crystal clear waters of Netrani Island - India's premier scuba diving destination! Also known as Pigeon Island, this heart-shaped island offers visibility up to 30 meters and vibrant marine life including reef sharks, rays, and colorful coral.\n\nNo prior diving experience needed! Our certified PADI instructors will guide you through every step. Also visit the magnificent Murudeshwar Temple with the world's second tallest Shiva statue.",
        highlights: ["Scuba diving at Netrani Island", "30m underwater visibility", "Marine life: sharks, rays, turtles", "Murudeshwar Temple visit", "World's 2nd tallest Shiva statue", "PADI certified instructors"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing and scuba introduction", "10:00 PM - Overnight journey to Murudeshwar"]},
            {day: "Day 1", title: "Scuba Diving Day", activities: ["6:00 AM - Arrive at Murudeshwar", "7:00 AM - Check-in, freshen up, breakfast", "8:30 AM - Scuba diving briefing and training", "10:00 AM - Boat ride to Netrani Island (1 hour)", "11:30 AM - Scuba diving session (45 mins underwater)", "1:00 PM - Return to shore, lunch", "3:00 PM - Rest and optional snorkeling", "5:00 PM - Murudeshwar Temple visit", "6:30 PM - Sunset at beach", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 2", title: "Temple & Return", activities: ["6:00 AM - Sunrise at Murudeshwar beach", "7:30 AM - Breakfast", "9:00 AM - Explore Murudeshwar Temple complex", "10:30 AM - Shopping for souvenirs", "12:00 PM - Lunch and departure", "8:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "1 Night hotel stay", "All meals", "Scuba diving with equipment", "PADI certified instructor", "Boat ride to island", "Temple visit"],
        excludes: ["Underwater photos/videos (₹500 extra)", "Personal expenses", "Travel insurance", "Tips"],
    },
    pondicherry: {
        title: "Pondicherry Trip",
        location: "Puducherry",
        badge: "Beach/Cultural",
        price: "₹4,977",
        image: "images/trips/pondicherry.jpg",
        distance: "310 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Oct - Mar",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Experience the French Riviera of the East! Pondicherry charms visitors with its unique blend of French colonial heritage, spiritual centers, pristine beaches, and vibrant cafes. Walk through the yellow-painted French Quarter, feel the peace at Auroville, and enjoy the laid-back beach vibes.\n\nFrom croissants at French bakeries to sunrise at Paradise Beach, Pondicherry offers a perfect blend of culture, spirituality, and relaxation.",
        highlights: ["French Quarter heritage walk", "Auroville Matrimandir visit", "Paradise Beach sunrise", "Promenade Beach evening", "French cafes and cuisine", "Sri Aurobindo Ashram"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Introduction and trip briefing", "10:00 PM - Overnight journey to Pondicherry"]},
            {day: "Day 1", title: "Pondicherry Exploration", activities: ["6:00 AM - Arrive in Pondicherry", "7:00 AM - Paradise Beach sunrise", "8:30 AM - Check-in and breakfast at French cafe", "10:00 AM - Auroville and Matrimandir visit", "1:00 PM - Lunch at Auroville cafe", "3:00 PM - French Quarter heritage walk", "4:30 PM - Sri Aurobindo Ashram", "6:00 PM - Promenade Beach sunset", "7:30 PM - Rock Beach stroll", "8:30 PM - Dinner at French restaurant"]},
            {day: "Day 2", title: "Beach & Return", activities: ["6:00 AM - Optional sunrise at beach", "8:00 AM - Breakfast", "9:30 AM - Serenity Beach visit", "11:00 AM - Shopping at MG Road", "12:30 PM - Lunch", "1:30 PM - Departure for Bangalore", "8:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "1 Night hotel stay", "Breakfast", "Paradise Beach boat ride", "Auroville entry", "Local guide"],
        excludes: ["Meals not mentioned", "Shopping", "Personal expenses", "Tips"],
    },
    "wayanad-pool-party": {
        title: "Wayanad Private Pool Party",
        location: "Wayanad, Kerala",
        badge: "Adventure",
        price: "₹6,477",
        image: "images/trips/wayanad-pool-party.jpg",
        distance: "280 km from Bangalore",
        elevation: "700-2,100 m",
        difficulty: "Easy",
        bestTime: "Sep - May",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Combine the beauty of Wayanad hills with an exclusive private pool party experience! Stay at a premium resort with private pool access, enjoy unlimited fun with music, games, and BBQ night.\n\nThis trip is perfect for friend groups and corporate outings looking for a mix of adventure and relaxation in the lap of nature.",
        highlights: ["Private pool party", "BBQ dinner night", "Music and DJ", "Wayanad sightseeing", "Premium resort stay", "Edakkal Caves trek"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Party mood begins in the bus!", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Pool Party Day", activities: ["5:30 AM - Arrive in Wayanad", "6:30 AM - Check-in to resort", "7:30 AM - Breakfast", "9:00 AM - Edakkal Caves trek", "12:00 PM - Return to resort, lunch", "2:00 PM - Pool party begins!", "2:30 PM - Pool games, music, fun", "5:00 PM - Snacks by the pool", "7:00 PM - Freshen up", "8:00 PM - BBQ dinner with bonfire", "10:00 PM - Music, dance, party night"]},
            {day: "Day 2", title: "Sightseeing & Return", activities: ["8:00 AM - Late breakfast", "9:30 AM - Soochipara Waterfalls", "11:30 AM - Pookode Lake", "1:00 PM - Lunch", "2:00 PM - Departure for Bangalore", "9:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "Premium resort with pool", "All meals", "BBQ dinner", "Pool access", "Sightseeing"],
        excludes: ["Alcoholic beverages", "Personal expenses", "Entry fees", "Tips"],
    },
    "madurai-rameswaram": {
        title: "Madurai-Rameswaram-Thanjavur",
        location: "Tamil Nadu",
        badge: "Heritage",
        price: "₹8,977",
        image: "images/trips/madurai-rameswaram.jpg",
        distance: "600 km from Bangalore",
        elevation: "Sea level - 100m",
        difficulty: "Easy",
        bestTime: "Oct - Mar",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Embark on a spiritual journey through Tamil Nadu's most magnificent temples! Visit the awe-inspiring Meenakshi Temple in Madurai, take a holy dip at Ramanathaswamy Temple in Rameswaram, and marvel at the architectural wonder of Brihadeeswarar Temple in Thanjavur.\n\nThis heritage trail covers three UNESCO-recognized sites and offers deep insights into Dravidian architecture and South Indian spirituality.",
        highlights: ["Meenakshi Amman Temple", "Ramanathaswamy Temple", "Dhanushkodi ghost town", "Brihadeeswarar Temple (UNESCO)", "Pamban Bridge view", "Traditional Tamil cuisine"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip briefing", "9:00 PM - Overnight journey to Madurai"]},
            {day: "Day 1", title: "Madurai & Rameswaram", activities: ["6:00 AM - Arrive in Madurai", "7:00 AM - Freshen up, breakfast", "8:00 AM - Meenakshi Amman Temple", "11:00 AM - Thirumalai Nayak Palace", "12:30 PM - Lunch", "1:30 PM - Drive to Rameswaram", "4:00 PM - Pamban Bridge photo stop", "5:00 PM - Ramanathaswamy Temple", "7:00 PM - Agni Theertham beach", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 2", title: "Dhanushkodi & Thanjavur", activities: ["5:00 AM - Dhanushkodi sunrise trip", "7:30 AM - Explore ghost town", "9:00 AM - Breakfast", "10:00 AM - Drive to Thanjavur", "2:00 PM - Lunch en route", "4:00 PM - Brihadeeswarar Temple", "6:00 PM - Thanjavur Palace", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 3", title: "Return Journey", activities: ["7:00 AM - Breakfast", "8:00 AM - Saraswathi Mahal Library", "10:00 AM - Departure for Bangalore", "8:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC Sleeper transport", "2 Nights hotel stay", "All meals", "Temple guide", "All sightseeing", "Dhanushkodi jeep"],
        excludes: ["Temple donations", "Special pooja charges", "Personal expenses", "Tips"],
    },
    "alleppey-varkala": {
        title: "Alleppey-Varkala-Athirappilly Falls",
        location: "Kerala",
        badge: "Road Trip",
        price: "₹9,877",
        image: "images/trips/alleppey-varkala.jpg",
        distance: "560 km from Bangalore",
        elevation: "Sea level - 300m",
        difficulty: "Easy",
        bestTime: "Sep - Mar",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Experience the best of Kerala in one epic road trip! Cruise through the serene Alleppey backwaters on a traditional houseboat, relax at the stunning Varkala cliff beach, and witness the majestic Athirappilly Falls - India's own Niagara.\n\nThis trip combines backwater tranquility, beach vibes, and waterfall adventure for the ultimate Kerala experience.",
        highlights: ["Alleppey houseboat overnight stay", "Varkala cliff beach", "Athirappilly Falls (Bahubali location)", "Kerala backwater cruise", "Traditional Kerala cuisine", "Sunset at Varkala"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trip introduction", "9:00 PM - Overnight journey to Alleppey"]},
            {day: "Day 1", title: "Alleppey Houseboat", activities: ["9:00 AM - Arrive in Alleppey", "10:00 AM - Freshen up, breakfast", "12:00 PM - Board traditional houseboat", "12:30 PM - Kerala lunch on houseboat", "1:00 PM - Cruise through backwaters", "4:00 PM - Tea and snacks on deck", "6:00 PM - Sunset on backwaters", "8:00 PM - Dinner on houseboat", "Night - Sleep under stars on deck"]},
            {day: "Day 2", title: "Varkala Beach Day", activities: ["7:00 AM - Wake up to backwater sunrise", "8:00 AM - Breakfast, disembark", "9:00 AM - Drive to Varkala", "12:00 PM - Arrive at Varkala cliff", "1:00 PM - Lunch at cliff cafe", "2:00 PM - Beach time and swimming", "4:00 PM - Cliff walk and cafes", "6:00 PM - Sunset at Varkala cliff", "8:00 PM - Dinner, overnight stay"]},
            {day: "Day 3", title: "Athirappilly Falls & Return", activities: ["6:00 AM - Breakfast", "7:00 AM - Drive to Athirappilly", "11:00 AM - Athirappilly Falls visit", "1:00 PM - Lunch near falls", "2:00 PM - Departure for Bangalore", "10:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC Sleeper transport", "1 Night houseboat (AC)", "1 Night hotel stay", "All meals", "All sightseeing", "Tour guide"],
        excludes: ["Water sports", "Personal expenses", "Entry fees", "Tips"],
    },
    "rameshwaram-dhanushkodi": {
        title: "Rameshwaram-Dhanushkodi-Srirangam",
        location: "Tamil Nadu",
        badge: "Heritage",
        price: "₹6,177",
        image: "images/trips/rameshwaram-dhanushkodi.jpg",
        distance: "550 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Easy",
        bestTime: "Oct - Mar",
        duration: "2D/1N",
        availableDates: ["Jan 11-12, 2026", "Jan 18-19, 2026", "Jan 25-26, 2026", "Feb 01-02, 2026", "Feb 08-09, 2026"],
        about: "Journey to the sacred island of Rameswaram, where Lord Rama built the legendary bridge to Lanka! Visit the magnificent Ramanathaswamy Temple with its stunning corridor of 1000 pillars, explore the haunting beauty of Dhanushkodi ghost town, and seek blessings at Srirangam's massive temple complex.\n\nThis spiritual circuit covers the most sacred sites associated with the Ramayana.",
        highlights: ["Ramanathaswamy Temple", "Dhanushkodi ghost town", "Pamban Bridge - India's first sea bridge", "Srirangam Ranganathaswamy Temple", "22 holy theerthams", "Agni Theertham beach"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Rameswaram & Dhanushkodi", activities: ["7:00 AM - Arrive in Rameswaram", "7:30 AM - Freshen up, breakfast", "8:30 AM - Agni Theertham holy bath", "9:30 AM - Ramanathaswamy Temple", "12:00 PM - 22 Theerthams ritual", "1:00 PM - Lunch", "2:30 PM - Jeep ride to Dhanushkodi", "3:30 PM - Explore ghost town", "5:00 PM - Dhanushkodi beach & tip of India", "6:30 PM - Return via Pamban Bridge sunset", "8:00 PM - Dinner and rest"]},
            {day: "Day 2", title: "Srirangam & Return", activities: ["5:00 AM - Early departure for Srirangam", "9:00 AM - Breakfast en route", "11:00 AM - Ranganathaswamy Temple", "1:00 PM - Lunch", "2:00 PM - Departure for Bangalore", "9:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "1 Night stay", "All meals", "Dhanushkodi jeep", "Temple guide", "All sightseeing"],
        excludes: ["Temple donations", "Special pooja", "Personal expenses", "Tips"],
    },
    "goa-waterfalls": {
        title: "Goa & Karnataka Waterfalls Trek",
        location: "Goa & Karnataka",
        badge: "Adventure",
        price: "₹5,477",
        image: "images/trips/goa-waterfalls.jpg",
        distance: "560 km from Bangalore",
        elevation: "Sea level - 600m",
        difficulty: "Moderate",
        bestTime: "Oct - Mar",
        duration: "2D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Combine the best of two worlds - Goa beaches and Karnataka's hidden waterfalls! This unique trip takes you to stunning waterfalls in the Western Ghats and then to the beaches of Goa for the perfect adventure-relaxation combo.\n\nTrek through lush forests to discover cascading waterfalls, take refreshing dips in natural pools, and end your trip with sunset at Goa's beaches.",
        highlights: ["Dudhsagar Falls viewpoint", "Hidden waterfall treks", "Natural pool swimming", "Goa beach exploration", "Western Ghats trekking", "Spice plantation visit"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["8:00 PM - Pickup from Bangalore", "8:30 PM - Trek briefing", "9:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Waterfall Treks", activities: ["6:00 AM - Arrive at Karnataka-Goa border", "7:00 AM - Breakfast", "8:00 AM - Trek to hidden waterfalls", "10:00 AM - Swim in natural pools", "12:00 PM - Packed lunch at waterfall", "2:00 PM - Continue to second waterfall", "4:00 PM - Spice plantation visit", "6:00 PM - Drive to Goa", "8:00 PM - Check-in, dinner at beach shack"]},
            {day: "Day 2", title: "Goa Beaches & Return", activities: ["6:00 AM - Sunrise at beach", "8:00 AM - Breakfast", "9:00 AM - Dudhsagar Falls viewpoint", "12:00 PM - Lunch", "1:00 PM - Departure for Bangalore", "10:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC Sleeper transport", "1 Night stay", "All meals", "Trek guide", "Spice plantation entry", "All sightseeing"],
        excludes: ["Water sports", "Personal expenses", "Entry fees", "Tips"],
    },
    "dandeli-netrani-scuba": {
        title: "Dandeli & Netrani Scuba Diving",
        location: "Dandeli & Murudeshwar",
        badge: "Adventure",
        price: "₹7,497",
        image: "images/trips/dandeli-netrani-scuba.jpg",
        distance: "490 km from Bangalore",
        elevation: "Sea level - 460m",
        difficulty: "Moderate",
        bestTime: "Oct - May",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "The ultimate Karnataka adventure combo! Experience white water rafting on Kali River in Dandeli and then dive into the crystal clear waters of Netrani Island for an unforgettable scuba diving experience.\n\nThis action-packed trip combines river rapids, jungle safari, and underwater exploration - perfect for adrenaline junkies looking for non-stop adventure!",
        highlights: ["White water rafting on Kali River", "Scuba diving at Netrani Island", "Jungle safari in Dandeli", "Murudeshwar Temple visit", "River kayaking", "Marine life exploration"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Adventure briefing", "10:00 PM - Overnight journey to Dandeli"]},
            {day: "Day 1", title: "Dandeli Adventures", activities: ["6:00 AM - Arrive at Dandeli", "7:00 AM - Check-in to riverside camp", "8:00 AM - Breakfast", "9:30 AM - White water rafting (2 hours)", "12:00 PM - Lunch at camp", "2:00 PM - Kayaking session", "4:00 PM - Jungle safari", "6:00 PM - Return to camp", "7:00 PM - Bonfire and BBQ dinner"]},
            {day: "Day 2", title: "Scuba Diving Day", activities: ["5:00 AM - Early departure for Murudeshwar", "8:00 AM - Breakfast en route", "10:00 AM - Scuba diving briefing", "11:00 AM - Boat ride to Netrani Island", "12:00 PM - Scuba diving session", "2:00 PM - Return to shore, lunch", "4:00 PM - Murudeshwar Temple visit", "6:00 PM - Beach sunset", "8:00 PM - Dinner and overnight stay"]},
            {day: "Day 3", title: "Return Journey", activities: ["7:00 AM - Breakfast", "8:00 AM - Departure for Bangalore", "6:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "2 Nights stay (camp + hotel)", "All meals", "Rafting & Kayaking", "Scuba diving with equipment", "Jungle safari", "All activities"],
        excludes: ["Underwater photos (₹500 extra)", "Personal expenses", "Travel insurance", "Tips"],
    },
    "scuba-day-trip": {
        title: "1 Day Scuba Diving Trip",
        location: "Murudeshwar, Karnataka",
        badge: "Day Trip",
        price: "₹3,177",
        image: "images/trips/scuba-day-trip.jpg",
        distance: "490 km from Bangalore",
        elevation: "Sea level",
        difficulty: "Moderate",
        bestTime: "Oct - May",
        duration: "1 Day",
        availableDates: ["Jan 11, 2026", "Jan 18, 2026", "Jan 25, 2026", "Feb 01, 2026", "Feb 08, 2026"],
        about: "Experience scuba diving without taking time off! This express trip departs Friday night and gets you diving at Netrani Island by Saturday morning. Perfect for busy professionals who want adventure without sacrificing too many days.\n\nNo experience needed - our PADI certified instructors will have you exploring underwater wonders in no time!",
        highlights: ["Express scuba diving trip", "Netrani Island dive", "PADI certified instructors", "Underwater marine life", "Murudeshwar Temple", "Minimal time commitment"],
        itinerary: [
            {day: "Day 1", title: "Scuba Express", activities: ["12:00 AM - Departure from Bangalore (Friday midnight)", "6:00 AM - Arrive Murudeshwar, freshen up", "7:00 AM - Breakfast", "8:00 AM - Scuba briefing and training", "9:30 AM - Boat to Netrani Island", "10:30 AM - Scuba diving session", "12:30 PM - Return to shore", "1:00 PM - Lunch", "2:30 PM - Murudeshwar Temple visit", "4:00 PM - Departure for Bangalore", "11:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "Breakfast and lunch", "Scuba diving with equipment", "PADI instructor", "Boat ride", "Temple visit"],
        excludes: ["Underwater photos/videos", "Personal expenses", "Dinner", "Tips"],
    },
    "wayanad-3-days": {
        title: "Wayanad 3 Days Trip",
        location: "Wayanad, Kerala",
        badge: "Hill Station",
        price: "₹6,977",
        image: "images/trips/wayanad-3-days.jpg",
        distance: "280 km from Bangalore",
        elevation: "700-2,100 m",
        difficulty: "Easy-Moderate",
        bestTime: "Sep - May",
        duration: "3D/2N",
        availableDates: ["Jan 10-12, 2026", "Jan 17-19, 2026", "Jan 24-26, 2026", "Jan 31-Feb 02, 2026", "Feb 07-09, 2026"],
        about: "Explore every corner of Wayanad in this comprehensive 3-day trip! From prehistoric Edakkal Caves to the heart-shaped lake at Chembra Peak, from thundering waterfalls to serene wildlife sanctuaries - this trip covers it all.\n\nWayanad's misty mountains, spice plantations, and diverse wildlife make it one of Kerala's most enchanting destinations. Take your time to soak it all in!",
        highlights: ["Chembra Peak heart-shaped lake", "Edakkal Caves prehistoric art", "Soochipara & Meenmutty Falls", "Wayanad Wildlife Sanctuary", "Banasura Sagar Dam", "Spice & tea plantations"],
        itinerary: [
            {day: "Day 0", title: "Night Departure", activities: ["9:00 PM - Pickup from Bangalore", "9:30 PM - Trip briefing", "10:00 PM - Overnight journey"]},
            {day: "Day 1", title: "Caves & Waterfalls", activities: ["5:30 AM - Arrive in Wayanad", "6:30 AM - Check-in, freshen up", "7:30 AM - Breakfast", "9:00 AM - Edakkal Caves trek", "12:00 PM - Lunch", "2:00 PM - Soochipara Waterfalls", "4:30 PM - Meenmutty Falls", "6:30 PM - Return to resort", "8:00 PM - Dinner"]},
            {day: "Day 2", title: "Chembra Peak & Wildlife", activities: ["5:00 AM - Early start for Chembra Peak", "6:00 AM - Trek begins", "9:00 AM - Heart-shaped lake viewpoint", "11:00 AM - Return, late breakfast", "1:00 PM - Lunch", "2:30 PM - Wildlife Safari", "5:00 PM - Banasura Sagar Dam", "6:30 PM - Sunset at dam", "8:00 PM - Bonfire dinner"]},
            {day: "Day 3", title: "Plantations & Return", activities: ["7:00 AM - Breakfast", "8:30 AM - Tea plantation visit", "10:00 AM - Spice garden tour", "11:30 AM - Pookode Lake", "1:00 PM - Lunch and shopping", "2:00 PM - Departure for Bangalore", "9:00 PM - Arrive in Bangalore"]}
        ],
        includes: ["AC transportation", "2 Nights resort stay", "All meals", "Chembra trek permit", "Wildlife safari", "All sightseeing", "Bonfire"],
        excludes: ["Entry fees", "Boating charges", "Personal expenses", "Tips"],
    }
};

function getTripData(tripId) {
    return tripsData[tripId] || tripsData['netravati'];
}
